// Generated by purs version 0.13.8
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Data_Either = require("../Data.Either/index.js");
var Effect = require("../Effect/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var EffectFnCanceler = function (x) {
    return x;
};
var EffectFnAff = function (x) {
    return x;
};
var fromEffectFnAff = function (v) {
    return Effect_Aff.makeAff(function (k) {
        return function __do() {
            var v1 = v(function ($2007) {
                return k(Data_Either.Left.create($2007))();
            }, function ($2008) {
                return k(Data_Either.Right.create($2008))();
            });
            return function (e) {
                return Effect_Aff.makeAff(function (k2) {
                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(function () {
                        return v1(e, function ($2009) {
                            return k2(Data_Either.Left.create($2009))();
                        }, function ($2010) {
                            return k2(Data_Either.Right.create($2010))();
                        });
                    })(function ($dollar__unused) {
                        return Control_Applicative.pure(Effect.applicativeEffect)(Effect_Aff.nonCanceler);
                    });
                });
            };
        };
    });
};
module.exports = {
    EffectFnAff: EffectFnAff,
    EffectFnCanceler: EffectFnCanceler,
    fromEffectFnAff: fromEffectFnAff
};
