// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Array from "../Data.Array/index.js";
import * as Data_List_Types from "../Data.List.Types/index.js";
import * as Data_Struct_Utils_ReifyKeyAndValueSymbols from "../Data.Struct.Utils.ReifyKeyAndValueSymbols/index.js";
var RRenameMany = function (rrenameMany) {
    this.rrenameMany = rrenameMany;
};
var rrenameManyFunction = function (dictListToRow) {
    return function (dictReifyKeyAndValueSymbols) {
        return function (dictRowToList) {
            return function (dictRowToList1) {
                return new RRenameMany(function (dictGRenameMany) {
                    return function (nameChanges) {
                        return function (record) {
                            var nameChanges$prime = Data_Array.fromFoldable(Data_List_Types.foldableList)(Data_Struct_Utils_ReifyKeyAndValueSymbols.reifyKeyAndValueSymbols(dictReifyKeyAndValueSymbols)()(nameChanges));
                            return $foreign.unsafeRenameManyFunction(nameChanges$prime, record);
                        };
                    };
                });
            };
        };
    };
};
var rrenameMany = function (dict) {
    return dict.rrenameMany;
};
export {
    RRenameMany,
    rrenameMany,
    rrenameManyFunction
};
