// Generated by purs version 0.13.8
"use strict";
var Data_Lens_Fold = require("../Data.Lens.Fold/index.js");
var Data_Lens_Getter = require("../Data.Lens.Getter/index.js");
var Data_Lens_Internal_Forget = require("../Data.Lens.Internal.Forget/index.js");
var Data_Lens_Iso_Newtype = require("../Data.Lens.Iso.Newtype/index.js");
var Data_Lens_Record = require("../Data.Lens.Record/index.js");
var Data_Maybe_First = require("../Data.Maybe.First/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Formless_Data_FormFieldResult = require("../Formless.Data.FormFieldResult/index.js");
var Formless_Types_Form = require("../Formless.Types.Form/index.js");
var _Field = function (dictIsSymbol) {
    return function (dictNewtype) {
        return function (dictCons) {
            return function (sym) {
                return function (dictStrong) {
                    var $2149 = Data_Lens_Iso_Newtype["_Newtype"](dictNewtype)(dictNewtype)(dictStrong.Profunctor0());
                    var $2150 = Data_Lens_Record.prop(dictIsSymbol)()()(sym)(dictStrong);
                    var $2151 = Data_Lens_Iso_Newtype["_Newtype"](Formless_Types_Form.newtypeFormField)(Formless_Types_Form.newtypeFormField)(dictStrong.Profunctor0());
                    return function ($2152) {
                        return $2149($2150($2151($2152)));
                    };
                };
            };
        };
    };
};
var _FieldInput = function (dictIsSymbol) {
    return function (dictNewtype) {
        return function (dictCons) {
            return function (sym) {
                return function (dictStrong) {
                    var $2153 = _Field(dictIsSymbol)(dictNewtype)()(sym)(dictStrong);
                    var $2154 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "input";
                    }))()()(Data_Symbol.SProxy.value)(dictStrong);
                    return function ($2155) {
                        return $2153($2154($2155));
                    };
                };
            };
        };
    };
};
var getInput = function (dictIsSymbol) {
    return function (dictNewtype) {
        return function (dictCons) {
            return function (sym) {
                return Data_Lens_Getter.view(_FieldInput(dictIsSymbol)(dictNewtype)()(sym)(Data_Lens_Internal_Forget.strongForget));
            };
        };
    };
};
var _FieldResult = function (dictIsSymbol) {
    return function (dictNewtype) {
        return function (dictCons) {
            return function (sym) {
                return function (dictStrong) {
                    var $2156 = _Field(dictIsSymbol)(dictNewtype)()(sym)(dictStrong);
                    var $2157 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "result";
                    }))()()(Data_Symbol.SProxy.value)(dictStrong);
                    return function ($2158) {
                        return $2156($2157($2158));
                    };
                };
            };
        };
    };
};
var _FieldError = function (dictIsSymbol) {
    return function (dictNewtype) {
        return function (dictCons) {
            return function (sym) {
                return function (dictWander) {
                    var $2159 = _FieldResult(dictIsSymbol)(dictNewtype)()(sym)(dictWander.Strong0());
                    var $2160 = Formless_Data_FormFieldResult["_Error"](dictWander.Choice1());
                    return function ($2161) {
                        return $2159($2160($2161));
                    };
                };
            };
        };
    };
};
var getError = function (dictIsSymbol) {
    return function (dictNewtype) {
        return function (dictCons) {
            return function (sym) {
                return Data_Lens_Fold.preview(_FieldError(dictIsSymbol)(dictNewtype)()(sym)(Data_Lens_Internal_Forget.wanderForget(Data_Maybe_First.monoidFirst)));
            };
        };
    };
};
module.exports = {
    getInput: getInput,
    getError: getError,
    "_Field": _Field,
    "_FieldInput": _FieldInput,
    "_FieldResult": _FieldResult,
    "_FieldError": _FieldError
};
