// Generated by purs version 0.13.8
"use strict";
var Conduit_Capability_Navigate = require("../Conduit.Capability.Navigate/index.js");
var Conduit_Capability_Resource_User = require("../Conduit.Capability.Resource.User/index.js");
var Conduit_Component_HTML_Header = require("../Conduit.Component.HTML.Header/index.js");
var Conduit_Component_HTML_Utils = require("../Conduit.Component.HTML.Utils/index.js");
var Conduit_Data_Avatar = require("../Conduit.Data.Avatar/index.js");
var Conduit_Data_Email = require("../Conduit.Data.Email/index.js");
var Conduit_Data_Route = require("../Conduit.Data.Route/index.js");
var Conduit_Data_Username = require("../Conduit.Data.Username/index.js");
var Conduit_Form_Field = require("../Conduit.Form.Field/index.js");
var Conduit_Form_Validation = require("../Conduit.Form.Validation/index.js");
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Control_Monad_State_Class = require("../Control.Monad.State.Class/index.js");
var Control_Semigroupoid = require("../Control.Semigroupoid/index.js");
var DOM_HTML_Indexed_InputType = require("../DOM.HTML.Indexed.InputType/index.js");
var Data_Eq = require("../Data.Eq/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Lens_Fold = require("../Data.Lens.Fold/index.js");
var Data_Lens_Internal_Forget = require("../Data.Lens.Internal.Forget/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Maybe_First = require("../Data.Maybe.First/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Newtype = require("../Data.Newtype/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Data_Unit = require("../Data.Unit/index.js");
var Formless_Action = require("../Formless.Action/index.js");
var Formless_Class_Initial = require("../Formless.Class.Initial/index.js");
var Formless_Component = require("../Formless.Component/index.js");
var Formless_Internal_Transform = require("../Formless.Internal.Transform/index.js");
var Formless_Query = require("../Formless.Query/index.js");
var Formless_Retrieve = require("../Formless.Retrieve/index.js");
var Formless_Transform_Record = require("../Formless.Transform.Record/index.js");
var Formless_Transform_Row = require("../Formless.Transform.Row/index.js");
var Formless_Types_Component = require("../Formless.Types.Component/index.js");
var Formless_Types_Form = require("../Formless.Types.Form/index.js");
var Formless_Validation = require("../Formless.Validation/index.js");
var Halogen_Component = require("../Halogen.Component/index.js");
var Halogen_HTML = require("../Halogen.HTML/index.js");
var Halogen_HTML_Core = require("../Halogen.HTML.Core/index.js");
var Halogen_HTML_Elements = require("../Halogen.HTML.Elements/index.js");
var Halogen_HTML_Events = require("../Halogen.HTML.Events/index.js");
var Halogen_HTML_Properties = require("../Halogen.HTML.Properties/index.js");
var Halogen_Query_HalogenM = require("../Halogen.Query.HalogenM/index.js");
var Heterogeneous_Mapping = require("../Heterogeneous.Mapping/index.js");
var Network_RemoteData = require("../Network.RemoteData/index.js");
var SettingsForm = function (x) {
    return x;
};
var Initialize = (function () {
    function Initialize() {

    };
    Initialize.value = new Initialize();
    return Initialize;
})();
var HandleForm = (function () {
    function HandleForm(value0) {
        this.value0 = value0;
    };
    HandleForm.create = function (value0) {
        return new HandleForm(value0);
    };
    return HandleForm;
})();
var LogUserOut = (function () {
    function LogUserOut() {

    };
    LogUserOut.value = new LogUserOut();
    return LogUserOut;
})();
var newtypeSettingsForm = new Data_Newtype.Newtype(function (n) {
    return n;
}, SettingsForm);
var component = function (dictMonadAff) {
    return function (dictNavigate) {
        return function (dictManageUser) {
            var render = function (v) {
                var formComponent = (function () {
                    var renderForm = function (v1) {
                        var proxies = Formless_Transform_Row.mkSProxies()(newtypeSettingsForm)(Formless_Transform_Row.makeSProxiesCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "bio";
                        }))()(Formless_Transform_Row.makeSProxiesCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "email";
                        }))()(Formless_Transform_Row.makeSProxiesCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "image";
                        }))()(Formless_Transform_Row.makeSProxiesCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "password";
                        }))()(Formless_Transform_Row.makeSProxiesCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "username";
                        }))()(Formless_Transform_Row.makeSProxiesNil))))))(Formless_Types_Form.FormProxy.value);
                        var username = Conduit_Form_Field.input(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "username";
                        }))(newtypeSettingsForm)(newtypeSettingsForm)()()(proxies.username)(v1.form)([ Halogen_HTML_Properties.placeholder("Your name"), Halogen_HTML_Properties.type_(Halogen_HTML_Core.isPropInputType)(DOM_HTML_Indexed_InputType.InputText.value) ]);
                        var password = Conduit_Form_Field.input(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "password";
                        }))(newtypeSettingsForm)(newtypeSettingsForm)()()(proxies.password)(v1.form)([ Halogen_HTML_Properties.placeholder("Password"), Halogen_HTML_Properties.type_(Halogen_HTML_Core.isPropInputType)(DOM_HTML_Indexed_InputType.InputPassword.value) ]);
                        var image = Conduit_Form_Field.input(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "image";
                        }))(newtypeSettingsForm)(newtypeSettingsForm)()()(proxies.image)(v1.form)([ Halogen_HTML_Properties.placeholder("URL of profile picture"), Halogen_HTML_Properties.type_(Halogen_HTML_Core.isPropInputType)(DOM_HTML_Indexed_InputType.InputText.value) ]);
                        var email = Conduit_Form_Field.input(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "email";
                        }))(newtypeSettingsForm)(newtypeSettingsForm)()()(proxies.email)(v1.form)([ Halogen_HTML_Properties.placeholder("Email"), Halogen_HTML_Properties.type_(Halogen_HTML_Core.isPropInputType)(DOM_HTML_Indexed_InputType.InputEmail.value) ]);
                        var bio = Halogen_HTML_Elements.fieldset([ Conduit_Component_HTML_Utils.css("form-group") ])([ Halogen_HTML_Elements.textarea([ Conduit_Component_HTML_Utils.css("form-control form-control-lg"), Halogen_HTML_Properties.placeholder("Short bio about you"), Halogen_HTML_Properties.rows(8), Halogen_HTML_Properties.value(Formless_Retrieve.getInput(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "bio";
                        }))(newtypeSettingsForm)()(proxies.bio)(v1.form)), Halogen_HTML_Events.onValueInput((function () {
                            var $719 = Formless_Action.setValidate(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                return "bio";
                            }))(newtypeSettingsForm)()(proxies.bio);
                            return function ($720) {
                                return Data_Maybe.Just.create($719($720));
                            };
                        })()) ]) ]);
                        return Halogen_HTML_Elements.form_([ Halogen_HTML_Elements.fieldset_([ image, username, bio, email, password, Conduit_Form_Field.submit("Update settings") ]) ]);
                    };
                    var formInput = function (v1) {
                        return {
                            validators: {
                                image: Conduit_Form_Validation.toOptional(Data_Monoid.monoidString)(Data_Eq.eqString)(dictManageUser.Monad0())(Conduit_Form_Validation.avatarFormat(dictManageUser.Monad0())),
                                username: Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.required(Data_Eq.eqString)(Data_Monoid.monoidString)(dictManageUser.Monad0()))(Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.minLength(dictManageUser.Monad0())(3))(Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.maxLength(dictManageUser.Monad0())(20))(Conduit_Form_Validation.usernameFormat(dictManageUser.Monad0())))),
                                bio: Formless_Validation.hoistFn_(dictManageUser.Monad0())(Control_Applicative.pure(Data_Maybe.applicativeMaybe)),
                                email: Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.required(Data_Eq.eqString)(Data_Monoid.monoidString)(dictManageUser.Monad0()))(Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.minLength(dictManageUser.Monad0())(3))(Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.maxLength(dictManageUser.Monad0())(50))(Conduit_Form_Validation.emailFormat(dictManageUser.Monad0())))),
                                password: Conduit_Form_Validation.toOptional(Data_Monoid.monoidString)(Data_Eq.eqString)(dictManageUser.Monad0())(Control_Semigroupoid.composeFlipped(Formless_Validation.semigroupoidValidation(dictManageUser.Monad0()))(Conduit_Form_Validation.minLength(dictManageUser.Monad0())(3))(Conduit_Form_Validation.maxLength(dictManageUser.Monad0())(20)))
                            },
                            initialInputs: Data_Maybe.Nothing.value
                        };
                    };
                    return Formless_Component.component(dictMonadAff)()()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))(Formless_Types_Form.eqInputField(Data_Eq.eqString)))()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))(Formless_Types_Form.eqInputField(Data_Eq.eqString)))()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))(Formless_Types_Form.eqInputField(Data_Eq.eqString)))()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))(Formless_Types_Form.eqInputField(Data_Eq.eqString)))()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))(Formless_Types_Form.eqInputField(Data_Eq.eqString)))(Formless_Internal_Transform.inputFieldsToFormFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))()(Formless_Internal_Transform.inputFieldsToFormFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))()(Formless_Internal_Transform.inputFieldsToFormFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))()(Formless_Internal_Transform.inputFieldsToFormFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))()(Formless_Internal_Transform.inputFieldsToFormFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))()(Formless_Internal_Transform.inputFieldsToFormFieldsNil)())())())())())(Formless_Internal_Transform.inputFieldsToInputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))()(Formless_Internal_Transform.inputFieldsToInputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))()(Formless_Internal_Transform.inputFieldsToInputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))()(Formless_Internal_Transform.inputFieldsToInputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))()(Formless_Internal_Transform.inputFieldsToInputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))()(Formless_Internal_Transform.inputFieldsToInputNil)())())())())())(Formless_Internal_Transform.consCountErrors(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))()(Formless_Internal_Transform.consCountErrors(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))()(Formless_Internal_Transform.consCountErrors(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))()(Formless_Internal_Transform.consCountErrors(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))()(Formless_Internal_Transform.consCountErrors(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))()(Formless_Internal_Transform.nilCountErrors))))))(Formless_Internal_Transform.consAllTouched(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))()(Formless_Internal_Transform.consAllTouched(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))()(Formless_Internal_Transform.consAllTouched(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))()(Formless_Internal_Transform.consAllTouched(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))()(Formless_Internal_Transform.consAllTouched(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))()(Formless_Internal_Transform.nilAllTouched))))))(Formless_Internal_Transform.setFormFieldsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))()(Formless_Internal_Transform.setFormFieldsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))()(Formless_Internal_Transform.setFormFieldsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))()(Formless_Internal_Transform.setFormFieldsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))()(Formless_Internal_Transform.setFormFieldsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))()(Formless_Internal_Transform.setFormFieldsTouchedNil)())())())())())(Formless_Internal_Transform.replaceFormFieldInputsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))(Formless_Types_Form.newtypeInputField)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.replaceFormFieldInputsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))(Formless_Types_Form.newtypeInputField)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.replaceFormFieldInputsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))(Formless_Types_Form.newtypeInputField)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.replaceFormFieldInputsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))(Formless_Types_Form.newtypeInputField)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.replaceFormFieldInputsTouchedCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))(Formless_Types_Form.newtypeInputField)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.replaceFormFieldInputsTouchedNil))))))(Formless_Internal_Transform.modifyAllCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))(Formless_Types_Form.newtypeInputFunction)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.modifyAllCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))(Formless_Types_Form.newtypeInputFunction)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.modifyAllCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))(Formless_Types_Form.newtypeInputFunction)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.modifyAllCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))(Formless_Types_Form.newtypeInputFunction)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.modifyAllCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))(Formless_Types_Form.newtypeInputFunction)(Formless_Types_Form.newtypeFormField)()()()(Formless_Internal_Transform.modifyAllNil))))))(Formless_Internal_Transform.applyToValidationCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))(dictManageUser.Monad0())()(newtypeSettingsForm)()()(Formless_Internal_Transform.applyToValidationCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))(dictManageUser.Monad0())()(newtypeSettingsForm)()()(Formless_Internal_Transform.applyToValidationCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))(dictManageUser.Monad0())()(newtypeSettingsForm)()()(Formless_Internal_Transform.applyToValidationCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))(dictManageUser.Monad0())()(newtypeSettingsForm)()()(Formless_Internal_Transform.applyToValidationCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))(dictManageUser.Monad0())()(newtypeSettingsForm)()()(Formless_Internal_Transform.applyToValidationNil(dictManageUser.Monad0())))))))(Formless_Internal_Transform.formFieldsToMaybeOutputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))()(Formless_Internal_Transform.formFieldsToMaybeOutputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))()(Formless_Internal_Transform.formFieldsToMaybeOutputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))()(Formless_Internal_Transform.formFieldsToMaybeOutputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))()(Formless_Internal_Transform.formFieldsToMaybeOutputCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))()(Formless_Internal_Transform.formFieldsToMaybeOutputNil)())())())())())(Formless_Transform_Row.mkInputFieldsFromRowCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "bio";
                    }))(Formless_Class_Initial.initialString)()(Formless_Transform_Row.mkInputFieldsFromRowCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "email";
                    }))(Formless_Class_Initial.initialString)()(Formless_Transform_Row.mkInputFieldsFromRowCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "image";
                    }))(Formless_Class_Initial.initialString)()(Formless_Transform_Row.mkInputFieldsFromRowCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "password";
                    }))(Formless_Class_Initial.initialString)()(Formless_Transform_Row.mkInputFieldsFromRowCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "username";
                    }))(Formless_Class_Initial.initialString)()(Formless_Transform_Row.mkInputFieldsFromRowNil)())())())())())(newtypeSettingsForm)(newtypeSettingsForm)(newtypeSettingsForm)(newtypeSettingsForm)(newtypeSettingsForm)(newtypeSettingsForm)(newtypeSettingsForm)(newtypeSettingsForm)()()()()()()()()()(formInput)({
                        render: renderForm,
                        handleAction: Formless_Component.defaultSpec.handleAction,
                        handleQuery: Formless_Component.defaultSpec.handleQuery,
                        handleEvent: Formless_Component.raiseResult(newtypeSettingsForm)(Heterogeneous_Mapping.hmapRecord()(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "bio";
                        }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.unwrapField(Formless_Types_Form.newtypeOutputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "email";
                        }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.unwrapField(Formless_Types_Form.newtypeOutputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "image";
                        }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.unwrapField(Formless_Types_Form.newtypeOutputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "password";
                        }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.unwrapField(Formless_Types_Form.newtypeOutputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                            return "username";
                        }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.unwrapField(Formless_Types_Form.newtypeOutputField)))(Heterogeneous_Mapping.mapRecordWithIndexNil)()())()())()())()())()())),
                        receive: Formless_Component.defaultSpec.receive,
                        initialize: Formless_Component.defaultSpec.initialize,
                        finalize: Formless_Component.defaultSpec.finalize
                    });
                })();
                var container = function (html) {
                    return Halogen_HTML_Elements.div_([ Conduit_Component_HTML_Header.header(Data_Lens_Fold.preview(Network_RemoteData["_Success"](Data_Lens_Internal_Forget.choiceForget(Data_Maybe_First.monoidFirst)))(v.profile))(Conduit_Data_Route.Settings.value), Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("settings-page") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("container page") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("row") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("col-md-6 offset-md-3 col-xs12") ])(html) ]) ]) ]) ]);
                };
                return container([ Halogen_HTML_Elements.h1([ Conduit_Component_HTML_Utils.css("text-xs-center") ])([ Halogen_HTML_Core.text("Your Settings") ]), Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "formless";
                }))(Data_Ord.ordUnit)(Formless_Types_Component["_formless"])(Data_Unit.unit)(formComponent)(Data_Unit.unit)(function ($721) {
                    return Data_Maybe.Just.create(HandleForm.create($721));
                }), Halogen_HTML_Elements.hr_, Halogen_HTML_Elements.button([ Conduit_Component_HTML_Utils.css("btn btn-outline-danger"), Halogen_HTML_Events.onClick(function (v1) {
                    return new Data_Maybe.Just(LogUserOut.value);
                }) ])([ Halogen_HTML_Core.text("Log out") ]) ]);
            };
            var handleAction = function (v) {
                if (v instanceof Initialize) {
                    return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                        var $707 = {};
                        for (var $708 in v1) {
                            if ({}.hasOwnProperty.call(v1, $708)) {
                                $707[$708] = v1[$708];
                            };
                        };
                        $707.profile = Network_RemoteData.Loading.value;
                        return $707;
                    }))(function ($dollar__unused) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_User.getCurrentUser(Conduit_Capability_Resource_User.manageUserHalogenM(dictManageUser)))(function (mbProfileWithEmail) {
                            return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                var $710 = {};
                                for (var $711 in v1) {
                                    if ({}.hasOwnProperty.call(v1, $711)) {
                                        $710[$711] = v1[$711];
                                    };
                                };
                                $710.profile = Network_RemoteData.fromMaybe(mbProfileWithEmail);
                                return $710;
                            }))(function ($dollar__unused) {
                                if (mbProfileWithEmail instanceof Data_Maybe.Nothing) {
                                    return Conduit_Capability_Navigate.logout(Conduit_Capability_Navigate.navigateHalogenM(dictNavigate));
                                };
                                if (mbProfileWithEmail instanceof Data_Maybe.Just) {
                                    var newInputs = Formless_Transform_Record.wrapInputFields(newtypeSettingsForm)(Heterogeneous_Mapping.hmapRecord()(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                        return "bio";
                                    }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.wrapField(Formless_Types_Form.newtypeInputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                        return "email";
                                    }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.wrapField(Formless_Types_Form.newtypeInputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                        return "image";
                                    }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.wrapField(Formless_Types_Form.newtypeInputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                        return "password";
                                    }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.wrapField(Formless_Types_Form.newtypeInputField)))(Heterogeneous_Mapping.mapRecordWithIndexCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                        return "username";
                                    }))(Heterogeneous_Mapping.constMapping(Formless_Transform_Record.wrapField(Formless_Types_Form.newtypeInputField)))(Heterogeneous_Mapping.mapRecordWithIndexNil)()())()())()())()())()()))({
                                        image: Data_Maybe.fromMaybe("")(Data_Functor.map(Data_Maybe.functorMaybe)(Conduit_Data_Avatar.toString)(mbProfileWithEmail.value0.image)),
                                        username: Conduit_Data_Username.toString(mbProfileWithEmail.value0.username),
                                        bio: Data_Maybe.fromMaybe("")(mbProfileWithEmail.value0.bio),
                                        email: Data_Newtype.unwrap(Conduit_Data_Email.newtypeEmail)(mbProfileWithEmail.value0.email),
                                        password: ""
                                    });
                                    return Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Halogen_Query_HalogenM.query()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                        return "formless";
                                    }))(Data_Ord.ordUnit)(Formless_Types_Component["_formless"])(Data_Unit.unit)(Formless_Query.asQuery(Formless_Action.loadForm(newInputs))));
                                };
                                throw new Error("Failed pattern match at Conduit.Page.Settings (line 76, column 7 - line 87, column 77): " + [ mbProfileWithEmail.constructor.name ]);
                            });
                        });
                    });
                };
                if (v instanceof HandleForm) {
                    return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_User.updateUser(Conduit_Capability_Resource_User.manageUserHalogenM(dictManageUser))(v.value0))(function ($dollar__unused) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_User.getCurrentUser(Conduit_Capability_Resource_User.manageUserHalogenM(dictManageUser)))(function (mbProfileWithEmail) {
                            return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                var $715 = {};
                                for (var $716 in v1) {
                                    if ({}.hasOwnProperty.call(v1, $716)) {
                                        $715[$716] = v1[$716];
                                    };
                                };
                                $715.profile = Network_RemoteData.fromMaybe(mbProfileWithEmail);
                                return $715;
                            });
                        });
                    });
                };
                if (v instanceof LogUserOut) {
                    return Conduit_Capability_Navigate.logout(Conduit_Capability_Navigate.navigateHalogenM(dictNavigate));
                };
                throw new Error("Failed pattern match at Conduit.Page.Settings (line 68, column 18 - line 94, column 25): " + [ v.constructor.name ]);
            };
            return Halogen_Component.mkComponent({
                initialState: function (v) {
                    return {
                        profile: Network_RemoteData.NotAsked.value
                    };
                },
                render: render,
                "eval": Halogen_Component.mkEval({
                    handleAction: handleAction,
                    handleQuery: Halogen_Component.defaultEval.handleQuery,
                    receive: Halogen_Component.defaultEval.receive,
                    initialize: new Data_Maybe.Just(Initialize.value),
                    finalize: Halogen_Component.defaultEval.finalize
                })
            });
        };
    };
};
module.exports = {
    SettingsForm: SettingsForm,
    Initialize: Initialize,
    HandleForm: HandleForm,
    LogUserOut: LogUserOut,
    component: component,
    newtypeSettingsForm: newtypeSettingsForm
};
