// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Nullable from "../Data.Nullable/index.js";
import * as Effect from "../Effect/index.js";
var parentNode = (function () {
    var $3055 = Data_Functor.map(Effect.functorEffect)(Data_Nullable.toMaybe);
    return function ($3056) {
        return $3055($foreign["_parentNode"]($3056));
    };
})();
var nextSibling = (function () {
    var $3057 = Data_Functor.map(Effect.functorEffect)(Data_Nullable.toMaybe);
    return function ($3058) {
        return $3057($foreign["_nextSibling"]($3058));
    };
})();
export {
    insertBefore,
    appendChild,
    removeChild
} from "./foreign.js";
export {
    parentNode,
    nextSibling
};
