// Generated by purs version 0.13.6
import * as Conduit_Data_Comment from "../Conduit.Data.Comment/index.js";
import * as Conduit_Data_Route from "../Conduit.Data.Route/index.js";
import * as Data_Generic_Rep from "../Data.Generic.Rep/index.js";
import * as Data_Lens_Iso_Newtype from "../Data.Lens.Iso.Newtype/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Symbol from "../Data.Symbol/index.js";
import * as Routing_Duplex from "../Routing.Duplex/index.js";
import * as Routing_Duplex_Generic from "../Routing.Duplex.Generic/index.js";
import * as Routing_Duplex_Generic_Syntax from "../Routing.Duplex.Generic.Syntax/index.js";
var Login = (function () {
    function Login() {

    };
    Login.value = new Login();
    return Login;
})();
var User = (function () {
    function User() {

    };
    User.value = new User();
    return User;
})();
var Users = (function () {
    function Users() {

    };
    Users.value = new Users();
    return Users;
})();
var Follow = (function () {
    function Follow(value0) {
        this.value0 = value0;
    };
    Follow.create = function (value0) {
        return new Follow(value0);
    };
    return Follow;
})();
var Article = (function () {
    function Article(value0) {
        this.value0 = value0;
    };
    Article.create = function (value0) {
        return new Article(value0);
    };
    return Article;
})();
var Comment = (function () {
    function Comment(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    Comment.create = function (value0) {
        return function (value1) {
            return new Comment(value0, value1);
        };
    };
    return Comment;
})();
var Comments = (function () {
    function Comments(value0) {
        this.value0 = value0;
    };
    Comments.create = function (value0) {
        return new Comments(value0);
    };
    return Comments;
})();
var Favorite = (function () {
    function Favorite(value0) {
        this.value0 = value0;
    };
    Favorite.create = function (value0) {
        return new Favorite(value0);
    };
    return Favorite;
})();
var Articles = (function () {
    function Articles(value0) {
        this.value0 = value0;
    };
    Articles.create = function (value0) {
        return new Articles(value0);
    };
    return Articles;
})();
var Profiles = (function () {
    function Profiles(value0) {
        this.value0 = value0;
    };
    Profiles.create = function (value0) {
        return new Profiles(value0);
    };
    return Profiles;
})();
var Feed = (function () {
    function Feed(value0) {
        this.value0 = value0;
    };
    Feed.create = function (value0) {
        return new Feed(value0);
    };
    return Feed;
})();
var Tags = (function () {
    function Tags() {

    };
    Tags.value = new Tags();
    return Tags;
})();
var noArticleParams = {
    tag: Data_Maybe.Nothing.value,
    author: Data_Maybe.Nothing.value,
    favorited: Data_Maybe.Nothing.value,
    offset: Data_Maybe.Nothing.value,
    limit: Data_Maybe.Nothing.value
};
var genericEndpoint = new Data_Generic_Rep.Generic(function (x) {
    if (x instanceof Login) {
        return new Data_Generic_Rep.Inl(Data_Generic_Rep.NoArguments.value);
    };
    if (x instanceof User) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(Data_Generic_Rep.NoArguments.value));
    };
    if (x instanceof Users) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(Data_Generic_Rep.NoArguments.value)));
    };
    if (x instanceof Follow) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0))));
    };
    if (x instanceof Article) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0)))));
    };
    if (x instanceof Comment) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(new Data_Generic_Rep.Product(x.value0, x.value1)))))));
    };
    if (x instanceof Comments) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0)))))));
    };
    if (x instanceof Favorite) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0))))))));
    };
    if (x instanceof Articles) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0)))))))));
    };
    if (x instanceof Profiles) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0))))))))));
    };
    if (x instanceof Feed) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inl(x.value0)))))))))));
    };
    if (x instanceof Tags) {
        return new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(new Data_Generic_Rep.Inr(Data_Generic_Rep.NoArguments.value)))))))))));
    };
    throw new Error("Failed pattern match at Conduit.Api.Endpoint (line 86, column 1 - line 86, column 54): " + [ x.constructor.name ]);
}, function (x) {
    if (x instanceof Data_Generic_Rep.Inl) {
        return Login.value;
    };
    if (x instanceof Data_Generic_Rep.Inr && x.value0 instanceof Data_Generic_Rep.Inl) {
        return User.value;
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0 instanceof Data_Generic_Rep.Inl)) {
        return Users.value;
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0 instanceof Data_Generic_Rep.Inl))) {
        return new Follow(x.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl)))) {
        return new Article(x.value0.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl))))) {
        return new Comment(x.value0.value0.value0.value0.value0.value0.value0, x.value0.value0.value0.value0.value0.value0.value1);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl)))))) {
        return new Comments(x.value0.value0.value0.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl))))))) {
        return new Favorite(x.value0.value0.value0.value0.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl)))))))) {
        return new Articles(x.value0.value0.value0.value0.value0.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl))))))))) {
        return new Profiles(x.value0.value0.value0.value0.value0.value0.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inl)))))))))) {
        return new Feed(x.value0.value0.value0.value0.value0.value0.value0.value0.value0.value0.value0);
    };
    if (x instanceof Data_Generic_Rep.Inr && (x.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && (x.value0.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr && x.value0.value0.value0.value0.value0.value0.value0.value0.value0.value0 instanceof Data_Generic_Rep.Inr)))))))))) {
        return Tags.value;
    };
    throw new Error("Failed pattern match at Conduit.Api.Endpoint (line 86, column 1 - line 86, column 54): " + [ x.constructor.name ]);
});
var commentId = Data_Lens_Iso_Newtype["_Newtype"](Conduit_Data_Comment.newtypeCommentId)(Conduit_Data_Comment.newtypeCommentId)(Routing_Duplex.profunctorRouteDuplex)(Routing_Duplex["int"](Routing_Duplex.segment));
var endpointCodec = Routing_Duplex.root(Routing_Duplex.prefix("api")(Routing_Duplex_Generic.sum(genericEndpoint)(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Login";
}))()(Routing_Duplex_Generic.gRouteNoArguments))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "User";
}))()(Routing_Duplex_Generic.gRouteNoArguments))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Users";
}))()(Routing_Duplex_Generic.gRouteNoArguments))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Follow";
}))()(Routing_Duplex_Generic.gRouteArgument))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Article";
}))()(Routing_Duplex_Generic.gRouteArgument))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Comment";
}))()(Routing_Duplex_Generic.gRouteProduct))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Comments";
}))()(Routing_Duplex_Generic.gRouteArgument))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Favorite";
}))()(Routing_Duplex_Generic.gRouteArgument))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Articles";
}))()(Routing_Duplex_Generic.gRouteAll))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Profiles";
}))()(Routing_Duplex_Generic.gRouteArgument))(Routing_Duplex_Generic.gRouteSum(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Feed";
}))()(Routing_Duplex_Generic.gRouteArgument))(Routing_Duplex_Generic.gRouteConstructor(new Data_Symbol.IsSymbol(function ($dollar__unused) {
    return "Tags";
}))()(Routing_Duplex_Generic.gRouteNoArguments)))))))))))))({
    Login: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteNoArguments))("users")(Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteNoArguments))("login")(Routing_Duplex_Generic.noArgs)),
    User: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteNoArguments))("user")(Routing_Duplex_Generic.noArgs),
    Users: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteNoArguments))("users")(Routing_Duplex_Generic.noArgs),
    Follow: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteArgument))("profiles")(Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepRouteString(Routing_Duplex_Generic.gRouteAll))(Conduit_Data_Route.uname(Routing_Duplex.segment))("follow")),
    Article: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteAll))("articles")(Conduit_Data_Route.slug(Routing_Duplex.segment)),
    Comments: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteArgument))("articles")(Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepRouteString(Routing_Duplex_Generic.gRouteAll))(Conduit_Data_Route.slug(Routing_Duplex.segment))("comments")),
    Comment: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteProduct))("articles")(Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepProduct(Routing_Duplex_Generic.gRouteArgument))(Conduit_Data_Route.slug(Routing_Duplex.segment))(Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteAll))("comments")(commentId))),
    Favorite: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteArgument))("articles")(Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepRouteString(Routing_Duplex_Generic.gRouteAll))(Conduit_Data_Route.slug(Routing_Duplex.segment))("favorite")),
    Articles: Routing_Duplex_Generic_Syntax.gparams(Routing_Duplex_Generic_Syntax.gparamsString(Routing_Duplex.routeDuplexParams()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "author";
    }))()()()()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "favorited";
    }))()()()()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "limit";
    }))()()()()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "offset";
    }))()()()()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "tag";
    }))()()()()(Routing_Duplex.buildParamsNil))))))))("articles")({
        tag: function ($165) {
            return Routing_Duplex.optional(Routing_Duplex.string($165));
        },
        author: function ($166) {
            return Routing_Duplex.optional(Conduit_Data_Route.uname($166));
        },
        favorited: function ($167) {
            return Routing_Duplex.optional(Conduit_Data_Route.uname($167));
        },
        offset: function ($168) {
            return Routing_Duplex.optional(Routing_Duplex["int"]($168));
        },
        limit: function ($169) {
            return Routing_Duplex.optional(Routing_Duplex["int"]($169));
        }
    }),
    Profiles: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteAll))("profiles")(Conduit_Data_Route.uname(Routing_Duplex.segment)),
    Feed: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteAll))("articles")(Routing_Duplex_Generic_Syntax.gparams(Routing_Duplex_Generic_Syntax.gparamsString(Routing_Duplex.routeDuplexParams()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "limit";
    }))()()()()(Routing_Duplex.buildParamsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "offset";
    }))()()()()(Routing_Duplex.buildParamsNil)))))("feed")({
        offset: function ($170) {
            return Routing_Duplex.optional(Routing_Duplex["int"]($170));
        },
        limit: function ($171) {
            return Routing_Duplex.optional(Routing_Duplex["int"]($171));
        }
    })),
    Tags: Routing_Duplex_Generic_Syntax.gsep(Routing_Duplex_Generic_Syntax.gsepStringRoute(Routing_Duplex_Generic.gRouteNoArguments))("tags")(Routing_Duplex_Generic.noArgs)
})));
export {
    noArticleParams,
    Login,
    User,
    Users,
    Follow,
    Article,
    Comment,
    Comments,
    Favorite,
    Articles,
    Profiles,
    Feed,
    Tags,
    endpointCodec,
    commentId,
    genericEndpoint
};
