// Generated by purs version 0.13.8
"use strict";
var Data_Monoid = require("../Data.Monoid/index.js");
var Initial = function (initial) {
    this.initial = initial;
};
var initialString = new Initial(Data_Monoid.mempty(Data_Monoid.monoidString));
var initialArray = new Initial(Data_Monoid.mempty(Data_Monoid.monoidArray));
var initial = function (dict) {
    return dict.initial;
};
module.exports = {
    initial: initial,
    Initial: Initial,
    initialString: initialString,
    initialArray: initialArray
};
