// Generated by purs version 0.13.6
import * as Data_Ring from "../Data.Ring/index.js";
var CommutativeRing = function (Ring0) {
    this.Ring0 = Ring0;
};
var commutativeRingNumber = new CommutativeRing(function ($dollar__unused) {
    return Data_Ring.ringNumber;
});
var commutativeRingInt = new CommutativeRing(function ($dollar__unused) {
    return Data_Ring.ringInt;
});
export {
    CommutativeRing,
    commutativeRingInt,
    commutativeRingNumber
};
