// Generated by purs version 0.13.6
import * as Component_HOC_Connect from "../Component.HOC.Connect/index.js";
import * as Conduit_Capability_Navigate from "../Conduit.Capability.Navigate/index.js";
import * as Conduit_Data_Route from "../Conduit.Data.Route/index.js";
import * as Conduit_Page_Editor from "../Conduit.Page.Editor/index.js";
import * as Conduit_Page_Home from "../Conduit.Page.Home/index.js";
import * as Conduit_Page_Login from "../Conduit.Page.Login/index.js";
import * as Conduit_Page_Profile from "../Conduit.Page.Profile/index.js";
import * as Conduit_Page_Register from "../Conduit.Page.Register/index.js";
import * as Conduit_Page_Settings from "../Conduit.Page.Settings/index.js";
import * as Conduit_Page_ViewArticle from "../Conduit.Page.ViewArticle/index.js";
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Monad_State_Class from "../Control.Monad.State.Class/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Symbol from "../Data.Symbol/index.js";
import * as Data_Unit from "../Data.Unit/index.js";
import * as Data_Void from "../Data.Void/index.js";
import * as Effect_Class from "../Effect.Class/index.js";
import * as Halogen_Component from "../Halogen.Component/index.js";
import * as Halogen_HTML from "../Halogen.HTML/index.js";
import * as Halogen_HTML_Core from "../Halogen.HTML.Core/index.js";
import * as Halogen_HTML_Elements from "../Halogen.HTML.Elements/index.js";
import * as Halogen_Query_HalogenM from "../Halogen.Query.HalogenM/index.js";
import * as Routing_Duplex from "../Routing.Duplex/index.js";
import * as Routing_Hash from "../Routing.Hash/index.js";
var Navigate = (function () {
    function Navigate(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    Navigate.create = function (value0) {
        return function (value1) {
            return new Navigate(value0, value1);
        };
    };
    return Navigate;
})();
var Initialize = (function () {
    function Initialize() {

    };
    Initialize.value = new Initialize();
    return Initialize;
})();
var Receive = (function () {
    function Receive(value0) {
        this.value0 = value0;
    };
    Receive.create = function (value0) {
        return new Receive(value0);
    };
    return Receive;
})();
var component = function (dictMonadAff) {
    return function (dictMonadAsk) {
        return function (dictNow) {
            return function (dictLogMessages) {
                return function (dictNavigate) {
                    return function (dictManageUser) {
                        return function (dictManageArticle) {
                            return function (dictManageComment) {
                                return function (dictManageTag) {
                                    var handleQuery = function (v) {
                                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (v1) {
                                            return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Applicative.when(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Eq.notEq(Data_Maybe.eqMaybe(Conduit_Data_Route.eqRoute))(v1.route)(new Data_Maybe.Just(v.value0)))((function () {
                                                var v2 = Data_Maybe.isJust(v1.currentUser) && Data_Foldable.elem(Data_Foldable.foldableArray)(Conduit_Data_Route.eqRoute)(v.value0)([ Conduit_Data_Route.Login.value, Conduit_Data_Route.Register.value ]);
                                                if (!v2) {
                                                    return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v3) {
                                                        var $327 = {};
                                                        for (var $328 in v3) {
                                                            if ({}.hasOwnProperty.call(v3, $328)) {
                                                                $327[$328] = v3[$328];
                                                            };
                                                        };
                                                        $327.route = new Data_Maybe.Just(v.value0);
                                                        return $327;
                                                    });
                                                };
                                                return Control_Applicative.pure(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Unit.unit);
                                            })()))(function ($dollar__unused) {
                                                return Control_Applicative.pure(Halogen_Query_HalogenM.applicativeHalogenM)(new Data_Maybe.Just(v.value1));
                                            });
                                        });
                                    };
                                    var handleAction = function (v) {
                                        if (v instanceof Initialize) {
                                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Data_Functor.map(Halogen_Query_HalogenM.functorHalogenM)((function () {
                                                var $354 = Routing_Duplex.parse(Conduit_Data_Route.routeCodec);
                                                return function ($355) {
                                                    return Data_Either.hush($354($355));
                                                };
                                            })())(Effect_Class.liftEffect(Halogen_Query_HalogenM.monadEffectHalogenM(dictMonadAff.MonadEffect0()))(Routing_Hash.getHash)))(function (initialRoute) {
                                                return Conduit_Capability_Navigate.navigate(Conduit_Capability_Navigate.navigateHalogenM(dictNavigate))(Data_Maybe.fromMaybe(Conduit_Data_Route.Home.value)(initialRoute));
                                            });
                                        };
                                        if (v instanceof Receive) {
                                            return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                                var $335 = {};
                                                for (var $336 in v1) {
                                                    if ({}.hasOwnProperty.call(v1, $336)) {
                                                        $335[$336] = v1[$336];
                                                    };
                                                };
                                                $335.currentUser = v.value0.currentUser;
                                                return $335;
                                            });
                                        };
                                        throw new Error("Failed pattern match at Conduit.Component.Router (line 89, column 18 - line 97, column 48): " + [ v.constructor.name ]);
                                    };
                                    var authorize = function (mbProfile) {
                                        return function (html) {
                                            if (mbProfile instanceof Data_Maybe.Nothing) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "login";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Login.component(dictMonadAff)(dictNavigate)(dictManageUser))({
                                                    redirect: false
                                                })(Data_Void.absurd);
                                            };
                                            if (mbProfile instanceof Data_Maybe.Just) {
                                                return html;
                                            };
                                            throw new Error("Failed pattern match at Conduit.Component.Router (line 115, column 30 - line 119, column 11): " + [ mbProfile.constructor.name ]);
                                        };
                                    };
                                    var render = function (v) {
                                        if (v.route instanceof Data_Maybe.Just) {
                                            if (v.route.value0 instanceof Conduit_Data_Route.Home) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "home";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Home.component(dictMonadAff)(dictMonadAsk)(dictNavigate)(dictManageTag)(dictManageArticle))({})(Data_Void.absurd);
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.Login) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "login";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Login.component(dictMonadAff)(dictNavigate)(dictManageUser))({
                                                    redirect: true
                                                })(Data_Void.absurd);
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.Register) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "register";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Register.component(dictMonadAff)(dictManageUser)(dictNavigate))(Data_Unit.unit)(Data_Void.absurd);
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.Settings) {
                                                return authorize(v.currentUser)(Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "settings";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Settings.component(dictMonadAff)(dictNavigate)(dictManageUser))(Data_Unit.unit)(Data_Void.absurd));
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.Editor) {
                                                return authorize(v.currentUser)(Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "editor";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Editor.component(dictMonadAff)(dictMonadAsk)(dictNavigate)(dictManageArticle))({
                                                    slug: Data_Maybe.Nothing.value
                                                })(Data_Void.absurd));
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.EditArticle) {
                                                return authorize(v.currentUser)(Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "editor";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Editor.component(dictMonadAff)(dictMonadAsk)(dictNavigate)(dictManageArticle))({
                                                    slug: new Data_Maybe.Just(v.route.value0.value0)
                                                })(Data_Void.absurd));
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.ViewArticle) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "viewArticle";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_ViewArticle.component(dictMonadAff)(dictManageArticle)(dictManageComment)(dictManageUser)(dictMonadAsk)(dictNavigate))({
                                                    slug: v.route.value0.value0
                                                })(Data_Void.absurd);
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.Profile) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "profile";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Profile.component(dictMonadAff)(dictMonadAsk)(dictManageUser)(dictManageArticle))({
                                                    username: v.route.value0.value0,
                                                    tab: Conduit_Page_Profile.ArticlesTab.value
                                                })(Data_Void.absurd);
                                            };
                                            if (v.route.value0 instanceof Conduit_Data_Route.Favorites) {
                                                return Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                                    return "profile";
                                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Page_Profile.component(dictMonadAff)(dictMonadAsk)(dictManageUser)(dictManageArticle))({
                                                    username: v.route.value0.value0,
                                                    tab: Conduit_Page_Profile.FavoritesTab.value
                                                })(Data_Void.absurd);
                                            };
                                            throw new Error("Failed pattern match at Conduit.Component.Router (line 123, column 15 - line 144, column 102): " + [ v.route.value0.constructor.name ]);
                                        };
                                        if (v.route instanceof Data_Maybe.Nothing) {
                                            return Halogen_HTML_Elements.div_([ Halogen_HTML_Core.text("Oh no! That page wasn't found.") ]);
                                        };
                                        throw new Error("Failed pattern match at Conduit.Component.Router (line 122, column 35 - line 146, column 59): " + [ v.route.constructor.name ]);
                                    };
                                    return Component_HOC_Connect.component(dictMonadAff)(dictMonadAsk)()(Halogen_Component.mkComponent({
                                        initialState: function (v) {
                                            return {
                                                route: Data_Maybe.Nothing.value,
                                                currentUser: v.currentUser
                                            };
                                        },
                                        render: render,
                                        "eval": Halogen_Component.mkEval({
                                            handleAction: handleAction,
                                            handleQuery: handleQuery,
                                            receive: function ($356) {
                                                return Data_Maybe.Just.create(Receive.create($356));
                                            },
                                            initialize: new Data_Maybe.Just(Initialize.value),
                                            finalize: Halogen_Component.defaultEval.finalize
                                        })
                                    }));
                                };
                            };
                        };
                    };
                };
            };
        };
    };
};
export {
    Navigate,
    Initialize,
    Receive,
    component
};
