// Generated by purs version 0.13.6
import * as Data_Symbol from "../Data.Symbol/index.js";
import * as Record from "../Record/index.js";
var RGet = function (rget) {
    this.rget = rget;
};
var rgetRecord = function (dictIsSymbol) {
    return function (dictSProxying) {
        return new RGet(function (dictCons) {
            return function (v) {
                return function (v1) {
                    return Record.get(dictIsSymbol)()(Data_Symbol.SProxy.value);
                };
            };
        });
    };
};
var rget = function (dict) {
    return dict.rget;
};
export {
    RGet,
    rget,
    rgetRecord
};
