// Generated by purs version 0.13.8
"use strict";
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Newtype = require("../Data.Newtype/index.js");
var Halogen_HTML_Core = require("../Halogen.HTML.Core/index.js");
var Halogen_Query_Input = require("../Halogen.Query.Input/index.js");
var ref = (function () {
    var go = function (p) {
        return function (mel) {
            return new Data_Maybe.Just(new Halogen_Query_Input.RefUpdate(p, mel));
        };
    };
    return function ($2373) {
        return Halogen_HTML_Core.ref(go($2373));
    };
})();
var prop = function (dictIsProp) {
    return Halogen_HTML_Core.prop(dictIsProp);
};
var rows = prop(Halogen_HTML_Core.isPropInt)("rows");
var src = prop(Halogen_HTML_Core.isPropString)("src");
var type_ = function (dictIsProp) {
    return prop(dictIsProp)("type");
};
var value = prop(Halogen_HTML_Core.isPropString)("value");
var placeholder = prop(Halogen_HTML_Core.isPropString)("placeholder");
var href = prop(Halogen_HTML_Core.isPropString)("href");
var class_ = (function () {
    var $2374 = prop(Halogen_HTML_Core.isPropString)("className");
    var $2375 = Data_Newtype.unwrap(Halogen_HTML_Core.newtypeClassName);
    return function ($2376) {
        return $2374($2375($2376));
    };
})();
var alt = prop(Halogen_HTML_Core.isPropString)("alt");
module.exports = {
    prop: prop,
    ref: ref,
    alt: alt,
    class_: class_,
    rows: rows,
    href: href,
    src: src,
    type_: type_,
    value: value,
    placeholder: placeholder
};
