// Generated by purs version 0.13.6
import * as Conduit_Capability_Resource_User from "../Conduit.Capability.Resource.User/index.js";
import * as Conduit_Component_HTML_Utils from "../Conduit.Component.HTML.Utils/index.js";
import * as Conduit_Data_Profile from "../Conduit.Data.Profile/index.js";
import * as Conduit_Data_Username from "../Conduit.Data.Username/index.js";
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Monad_State_Class from "../Control.Monad.State.Class/index.js";
import * as Control_Monad_Trans_Class from "../Control.Monad.Trans.Class/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Lens_Fold from "../Data.Lens.Fold/index.js";
import * as Data_Lens_Internal_Forget from "../Data.Lens.Internal.Forget/index.js";
import * as Data_Lens_Internal_Wander from "../Data.Lens.Internal.Wander/index.js";
import * as Data_Lens_Setter from "../Data.Lens.Setter/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Maybe_First from "../Data.Maybe.First/index.js";
import * as Halogen_HTML_Core from "../Halogen.HTML.Core/index.js";
import * as Halogen_HTML_Elements from "../Halogen.HTML.Elements/index.js";
import * as Halogen_HTML_Events from "../Halogen.HTML.Events/index.js";
import * as Halogen_Query_HalogenM from "../Halogen.Query.HalogenM/index.js";
var followButton = function (followAct) {
    return function (unfollowAct) {
        return function (author) {
            if (author.relation instanceof Conduit_Data_Profile.Following) {
                return Halogen_HTML_Elements.button([ Conduit_Component_HTML_Utils.css("btn btn-sm action-btn btn-secondary"), Halogen_HTML_Events.onClick(function (v) {
                    return new Data_Maybe.Just(unfollowAct);
                }) ])([ Halogen_HTML_Core.text(" Unfollow " + Conduit_Data_Username.toString(author.username)) ]);
            };
            if (author.relation instanceof Conduit_Data_Profile.NotFollowing) {
                return Halogen_HTML_Elements.button([ Conduit_Component_HTML_Utils.css("btn btn-sm action-btn btn-outline-secondary"), Halogen_HTML_Events.onClick(function (v) {
                    return new Data_Maybe.Just(followAct);
                }) ])([ Halogen_HTML_Elements.i([ Conduit_Component_HTML_Utils.css("ion-plus-round") ])([  ]), Halogen_HTML_Core.text(" Follow " + Conduit_Data_Username.toString(author.username)) ]);
            };
            if (author.relation instanceof Conduit_Data_Profile.You) {
                return Halogen_HTML_Core.text("");
            };
            throw new Error("Failed pattern match at Conduit.Component.Part.FollowButton (line 30, column 45 - line 47, column 20): " + [ author.relation.constructor.name ]);
        };
    };
};
var act = function (dictManageUser) {
    return function (cond) {
        return function (f) {
            return function (_author) {
                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (st) {
                    return Data_Foldable.for_(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Foldable.foldableMaybe)(Data_Lens_Fold.preview(_author(Data_Lens_Internal_Forget.wanderForget(Data_Maybe_First.monoidFirst)))(st))(function (author) {
                        return Control_Applicative.when(Halogen_Query_HalogenM.applicativeHalogenM)(cond(author))(Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_Trans_Class.lift(Halogen_Query_HalogenM.monadTransHalogenM)(dictManageUser.Monad0())(f(author.username)))(function (mbProfile) {
                            return Data_Foldable.for_(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Foldable.foldableMaybe)(mbProfile)((function () {
                                var $304 = Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM);
                                var $305 = Data_Lens_Setter.set(_author(Data_Lens_Internal_Wander.wanderFunction));
                                return function ($306) {
                                    return $304($305($306));
                                };
                            })());
                        }));
                    });
                });
            };
        };
    };
};
var follow = function (dictManageUser) {
    return function (_author) {
        return act(dictManageUser)((function () {
            var $307 = Data_Eq.eq(Conduit_Data_Profile.eqRelation)(Conduit_Data_Profile.NotFollowing.value);
            return function ($308) {
                return $307((function (v) {
                    return v.relation;
                })($308));
            };
        })())(Conduit_Capability_Resource_User.followUser(dictManageUser))(function (dictWander) {
            return _author(dictWander);
        });
    };
};
var unfollow = function (dictManageUser) {
    return function (_author) {
        return act(dictManageUser)((function () {
            var $309 = Data_Eq.eq(Conduit_Data_Profile.eqRelation)(Conduit_Data_Profile.Following.value);
            return function ($310) {
                return $309((function (v) {
                    return v.relation;
                })($310));
            };
        })())(Conduit_Capability_Resource_User.unfollowUser(dictManageUser))(function (dictWander) {
            return _author(dictWander);
        });
    };
};
export {
    followButton,
    follow,
    unfollow
};
