// Generated by purs version 0.13.6
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Apply from "../Control.Apply/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Monoid from "../Data.Monoid/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
var Const = function (x) {
    return x;
};
var newtypeConst = new Data_Newtype.Newtype(function (n) {
    return n;
}, Const);
var functorConst = new Data_Functor.Functor(function (f) {
    return function (m) {
        return m;
    };
});
var applyConst = function (dictSemigroup) {
    return new Control_Apply.Apply(function ($dollar__unused) {
        return functorConst;
    }, function (v) {
        return function (v1) {
            return Data_Semigroup.append(dictSemigroup)(v)(v1);
        };
    });
};
var applicativeConst = function (dictMonoid) {
    return new Control_Applicative.Applicative(function ($dollar__unused) {
        return applyConst(dictMonoid.Semigroup0());
    }, function (v) {
        return Data_Monoid.mempty(dictMonoid);
    });
};
export {
    Const,
    newtypeConst,
    functorConst,
    applyConst,
    applicativeConst
};
