// Generated by purs version 0.13.6
import * as DOM_HTML_Indexed_ButtonType from "../DOM.HTML.Indexed.ButtonType/index.js";
import * as DOM_HTML_Indexed_InputType from "../DOM.HTML.Indexed.InputType/index.js";
import * as Data_Bifunctor from "../Data.Bifunctor/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Halogen_Query_Input from "../Halogen.Query.Input/index.js";
import * as Halogen_VDom_DOM_Prop from "../Halogen.VDom.DOM.Prop/index.js";
import * as Halogen_VDom_Types from "../Halogen.VDom.Types/index.js";
var PropName = function (x) {
    return x;
};
var IsProp = function (toPropValue) {
    this.toPropValue = toPropValue;
};
var HTML = function (x) {
    return x;
};
var ClassName = function (x) {
    return x;
};
var widget = function ($2362) {
    return HTML(Halogen_VDom_Types.Widget.create($2362));
};
var toPropValue = function (dict) {
    return dict.toPropValue;
};
var text = function ($2363) {
    return HTML(Halogen_VDom_Types.Text.create($2363));
};
var ref = function (f) {
    return Halogen_VDom_DOM_Prop.Ref.create(function ($2364) {
        return f((function (v) {
            if (v instanceof Halogen_VDom_DOM_Prop.Created) {
                return new Data_Maybe.Just(v.value0);
            };
            if (v instanceof Halogen_VDom_DOM_Prop.Removed) {
                return Data_Maybe.Nothing.value;
            };
            throw new Error("Failed pattern match at Halogen.HTML.Core (line 104, column 21 - line 106, column 23): " + [ v.constructor.name ]);
        })($2364));
    });
};
var prop = function (dictIsProp) {
    return function (v) {
        var $2365 = Halogen_VDom_DOM_Prop.Property.create(v);
        var $2366 = toPropValue(dictIsProp);
        return function ($2367) {
            return $2365($2366($2367));
        };
    };
};
var newtypeHTML = new Data_Newtype.Newtype(function (n) {
    return n;
}, HTML);
var newtypeClassName = new Data_Newtype.Newtype(function (n) {
    return n;
}, ClassName);
var isPropString = new IsProp(Halogen_VDom_DOM_Prop.propFromString);
var isPropInt = new IsProp(Halogen_VDom_DOM_Prop.propFromInt);
var isPropInputType = new IsProp(function ($2368) {
    return Halogen_VDom_DOM_Prop.propFromString(DOM_HTML_Indexed_InputType.renderInputType($2368));
});
var isPropButtonType = new IsProp(function ($2369) {
    return Halogen_VDom_DOM_Prop.propFromString(DOM_HTML_Indexed_ButtonType.renderButtonType($2369));
});
var handler = Halogen_VDom_DOM_Prop.Handler.create;
var element = function (ns) {
    return function (name) {
        return function (props) {
            return function (children) {
                return new Halogen_VDom_Types.Elem(ns, name, props, children);
            };
        };
    };
};
var bifunctorHTML = new Data_Bifunctor.Bifunctor(function (f) {
    return function (g) {
        return function (v) {
            return Data_Bifunctor.bimap(Halogen_VDom_Types.bifunctorVDom)(Data_Functor.map(Data_Functor.functorArray)(Data_Functor.map(Halogen_VDom_DOM_Prop.functorProp)(Data_Functor.map(Halogen_Query_Input.functorInput)(g))))(f)(v);
        };
    };
});
export {
    HTML,
    widget,
    text,
    element,
    prop,
    handler,
    ref,
    IsProp,
    toPropValue,
    PropName,
    ClassName,
    newtypeHTML,
    bifunctorHTML,
    isPropString,
    isPropInt,
    isPropButtonType,
    isPropInputType,
    newtypeClassName
};
