// Generated by purs version 0.13.8
"use strict";
var Data_List_Types = require("../Data.List.Types/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Data_Tuple = require("../Data.Tuple/index.js");
var Type_Data_RowList = require("../Type.Data.RowList/index.js");
var ReifyKeyAndValueSymbols = function (reifyKeyAndValueSymbols$prime) {
    this["reifyKeyAndValueSymbols'"] = reifyKeyAndValueSymbols$prime;
};
var reifyKeyAndValueSymbolsNil = new ReifyKeyAndValueSymbols(Data_Monoid.mempty(Data_Monoid.monoidFn(Data_List_Types.monoidList)));
var reifyKeyAndValueSymbols$prime = function (dict) {
    return dict["reifyKeyAndValueSymbols'"];
};
var reifyKeyAndValueSymbolsCons = function (dictIsSymbol) {
    return function (dictIsSymbol1) {
        return function (dictReifyKeyAndValueSymbols) {
            return new ReifyKeyAndValueSymbols(function (v) {
                var string1 = Data_Symbol.reflectSymbol(dictIsSymbol1)(Data_Symbol.SProxy.value);
                var string0 = Data_Symbol.reflectSymbol(dictIsSymbol)(Data_Symbol.SProxy.value);
                var rest = reifyKeyAndValueSymbols$prime(dictReifyKeyAndValueSymbols)(Type_Data_RowList.RLProxy.value);
                return new Data_List_Types.Cons(new Data_Tuple.Tuple(string0, string1), rest);
            });
        };
    };
};
var reifyKeyAndValueSymbols = function (dictReifyKeyAndValueSymbols) {
    return function (dictRowToList) {
        return function (v) {
            return reifyKeyAndValueSymbols$prime(dictReifyKeyAndValueSymbols)(Type_Data_RowList.RLProxy.value);
        };
    };
};
module.exports = {
    ReifyKeyAndValueSymbols: ReifyKeyAndValueSymbols,
    reifyKeyAndValueSymbols: reifyKeyAndValueSymbols,
    "reifyKeyAndValueSymbols'": reifyKeyAndValueSymbols$prime,
    reifyKeyAndValueSymbolsNil: reifyKeyAndValueSymbolsNil,
    reifyKeyAndValueSymbolsCons: reifyKeyAndValueSymbolsCons
};
