// Generated by purs version 0.13.6
import * as Data_Profunctor from "../Data.Profunctor/index.js";
var iso = function (f) {
    return function (g) {
        return function (dictProfunctor) {
            return function (pab) {
                return Data_Profunctor.dimap(dictProfunctor)(f)(g)(pab);
            };
        };
    };
};
export {
    iso
};
