// Generated by purs version 0.13.6
import * as Effect_Aff from "../Effect.Aff/index.js";
var MonadFork = function (Functor1, Monad0, fork, join, suspend) {
    this.Functor1 = Functor1;
    this.Monad0 = Monad0;
    this.fork = fork;
    this.join = join;
    this.suspend = suspend;
};
var monadForkAff = new MonadFork(function ($dollar__unused) {
    return Effect_Aff.functorFiber;
}, function ($dollar__unused) {
    return Effect_Aff.monadAff;
}, Effect_Aff.forkAff, Effect_Aff.joinFiber, Effect_Aff.suspendAff);
var fork = function (dict) {
    return dict.fork;
};
export {
    fork,
    MonadFork,
    monadForkAff
};
