// Generated by purs version 0.13.6
import * as Conduit_Capability_Navigate from "../Conduit.Capability.Navigate/index.js";
import * as Conduit_Capability_Resource_Article from "../Conduit.Capability.Resource.Article/index.js";
import * as Conduit_Capability_Resource_Comment from "../Conduit.Capability.Resource.Comment/index.js";
import * as Conduit_Component_HTML_Footer from "../Conduit.Component.HTML.Footer/index.js";
import * as Conduit_Component_HTML_Header from "../Conduit.Component.HTML.Header/index.js";
import * as Conduit_Component_HTML_Utils from "../Conduit.Component.HTML.Utils/index.js";
import * as Conduit_Component_Part_FavoriteButton from "../Conduit.Component.Part.FavoriteButton/index.js";
import * as Conduit_Component_Part_FollowButton from "../Conduit.Component.Part.FollowButton/index.js";
import * as Conduit_Component_RawHTML from "../Conduit.Component.RawHTML/index.js";
import * as Conduit_Data_Avatar from "../Conduit.Data.Avatar/index.js";
import * as Conduit_Data_PreciseDateTime from "../Conduit.Data.PreciseDateTime/index.js";
import * as Conduit_Data_Profile from "../Conduit.Data.Profile/index.js";
import * as Conduit_Data_Route from "../Conduit.Data.Route/index.js";
import * as Conduit_Data_Username from "../Conduit.Data.Username/index.js";
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Monad_Reader_Class from "../Control.Monad.Reader.Class/index.js";
import * as Control_Monad_State_Class from "../Control.Monad.State.Class/index.js";
import * as Control_Parallel from "../Control.Parallel/index.js";
import * as DOM_HTML_Indexed_ButtonType from "../DOM.HTML.Indexed.ButtonType/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Lens_Fold from "../Data.Lens.Fold/index.js";
import * as Data_Lens_Internal_Forget from "../Data.Lens.Internal.Forget/index.js";
import * as Data_Lens_Record from "../Data.Lens.Record/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Maybe_First from "../Data.Maybe.First/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
import * as Data_Symbol from "../Data.Symbol/index.js";
import * as Data_Unit from "../Data.Unit/index.js";
import * as Data_Void from "../Data.Void/index.js";
import * as Effect_Class from "../Effect.Class/index.js";
import * as Effect_Ref from "../Effect.Ref/index.js";
import * as Halogen_Component from "../Halogen.Component/index.js";
import * as Halogen_HTML from "../Halogen.HTML/index.js";
import * as Halogen_HTML_Core from "../Halogen.HTML.Core/index.js";
import * as Halogen_HTML_Elements from "../Halogen.HTML.Elements/index.js";
import * as Halogen_HTML_Events from "../Halogen.HTML.Events/index.js";
import * as Halogen_HTML_Properties from "../Halogen.HTML.Properties/index.js";
import * as Halogen_Query_HalogenM from "../Halogen.Query.HalogenM/index.js";
import * as Network_RemoteData from "../Network.RemoteData/index.js";
import * as Slug from "../Slug/index.js";
var Initialize = (function () {
    function Initialize() {

    };
    Initialize.value = new Initialize();
    return Initialize;
})();
var GetArticle = (function () {
    function GetArticle() {

    };
    GetArticle.value = new GetArticle();
    return GetArticle;
})();
var GetComments = (function () {
    function GetComments() {

    };
    GetComments.value = new GetComments();
    return GetComments;
})();
var AddComment = (function () {
    function AddComment() {

    };
    AddComment.value = new AddComment();
    return AddComment;
})();
var UpdateCommentText = (function () {
    function UpdateCommentText(value0) {
        this.value0 = value0;
    };
    UpdateCommentText.create = function (value0) {
        return new UpdateCommentText(value0);
    };
    return UpdateCommentText;
})();
var FollowAuthor = (function () {
    function FollowAuthor() {

    };
    FollowAuthor.value = new FollowAuthor();
    return FollowAuthor;
})();
var UnfollowAuthor = (function () {
    function UnfollowAuthor() {

    };
    UnfollowAuthor.value = new UnfollowAuthor();
    return UnfollowAuthor;
})();
var FavoriteArticle = (function () {
    function FavoriteArticle() {

    };
    FavoriteArticle.value = new FavoriteArticle();
    return FavoriteArticle;
})();
var UnfavoriteArticle = (function () {
    function UnfavoriteArticle() {

    };
    UnfavoriteArticle.value = new UnfavoriteArticle();
    return UnfavoriteArticle;
})();
var DeleteArticle = (function () {
    function DeleteArticle() {

    };
    DeleteArticle.value = new DeleteArticle();
    return DeleteArticle;
})();
var DeleteComment = (function () {
    function DeleteComment(value0) {
        this.value0 = value0;
    };
    DeleteComment.create = function (value0) {
        return new DeleteComment(value0);
    };
    return DeleteComment;
})();
var Receive = (function () {
    function Receive(value0) {
        this.value0 = value0;
    };
    Receive.create = function (value0) {
        return new Receive(value0);
    };
    return Receive;
})();
var component = function (dictMonadAff) {
    return function (dictManageArticle) {
        return function (dictManageComment) {
            return function (dictManageUser) {
                return function (dictMonadAsk) {
                    return function (dictNavigate) {
                        var render = function (state) {
                            var viewComment = function (comment) {
                                return Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("card") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("card-block") ])([ Halogen_HTML_Elements.p([ Conduit_Component_HTML_Utils.css("card-text") ])([ Halogen_HTML_Core.text(comment.body) ]) ]), Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("card-footer") ])([ Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("comment-author"), Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.Profile(comment.author.username)) ])([ Halogen_HTML_Elements.img([ Conduit_Component_HTML_Utils.css("comment-author-img"), Halogen_HTML_Properties.src(Conduit_Data_Avatar.toStringWithDefault(comment.author.image)) ]) ]), Halogen_HTML_Core.text(" "), Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("comment-author"), Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.Profile(comment.author.username)) ])([ Halogen_HTML_Core.text(Conduit_Data_Username.toString(comment.author.username)) ]), Halogen_HTML_Core.text(" "), Halogen_HTML_Elements.span([ Conduit_Component_HTML_Utils.css("date-posted") ])([ Halogen_HTML_Core.text(Conduit_Data_PreciseDateTime.toDisplayMonthDayYear(comment.createdAt)) ]), Conduit_Component_HTML_Utils.whenElem(Data_Eq.eq(Conduit_Data_Profile.eqRelation)(comment.author.relation)(Conduit_Data_Profile.You.value))(function (v) {
                                    return Halogen_HTML_Elements.span([ Conduit_Component_HTML_Utils.css("mod-options") ])([ Halogen_HTML_Elements.i([ Conduit_Component_HTML_Utils.css("ion-trash-a"), Halogen_HTML_Events.onClick(function (v1) {
                                        return Data_Maybe.Just.create(new DeleteComment(comment.id));
                                    }) ])([  ]) ]);
                                }) ]) ]);
                            };
                            var mbArticle = Data_Lens_Fold.preview(Network_RemoteData["_Success"](Data_Lens_Internal_Forget.choiceForget(Data_Maybe_First.monoidFirst)))(state.article);
                            var markdown = Data_Maybe.fromMaybe("Failed to load article!")(Data_Functor.map(Data_Maybe.functorMaybe)(function (v) {
                                return v.body;
                            })(mbArticle));
                            var articleMeta = function (article) {
                                return Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("article-meta") ])([ Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.Profile(article.author.username)) ])([ Halogen_HTML_Elements.img([ Halogen_HTML_Properties.src(Conduit_Data_Avatar.toStringWithDefault(article.author.image)) ]) ]), Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("info") ])([ Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("author"), Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.Profile(article.author.username)) ])([ Halogen_HTML_Core.text(Conduit_Data_Username.toString(article.author.username)) ]), Halogen_HTML_Elements.span([ Conduit_Component_HTML_Utils.css("date") ])([ Halogen_HTML_Core.text(Conduit_Data_PreciseDateTime.toDisplayMonthDayYear(article.createdAt)) ]) ]), (function () {
                                    if (state.currentUser instanceof Data_Maybe.Just && Data_Eq.eq(Conduit_Data_Username.eqUsername)(state.currentUser.value0.username)(article.author.username)) {
                                        return Halogen_HTML_Elements.span_([ Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("btn btn-outline-secondary btn-sm"), Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.EditArticle(article.slug)) ])([ Halogen_HTML_Elements.i([ Conduit_Component_HTML_Utils.css("ion-edit") ])([  ]), Halogen_HTML_Core.text(" Edit Article") ]), Halogen_HTML_Core.text(" "), Halogen_HTML_Elements.button([ Conduit_Component_HTML_Utils.css("btn btn-outline-danger btn-sm"), Halogen_HTML_Events.onClick(function (v) {
                                            return new Data_Maybe.Just(DeleteArticle.value);
                                        }) ])([ Halogen_HTML_Elements.i([ Conduit_Component_HTML_Utils.css("ion-trash-a") ])([  ]), Halogen_HTML_Core.text(" Delete Article") ]) ]);
                                    };
                                    return Halogen_HTML_Elements.span_([ Conduit_Component_Part_FollowButton.followButton(FollowAuthor.value)(UnfollowAuthor.value)(article.author), Halogen_HTML_Core.text(" "), Conduit_Component_Part_FavoriteButton.favoriteButton(Conduit_Component_Part_FavoriteButton.Medium.value)(FavoriteArticle.value)(UnfavoriteArticle.value)(article) ]);
                                })() ]);
                            };
                            var banner = function (article) {
                                return Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("banner") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("container") ])([ Halogen_HTML_Elements.h1_([ Halogen_HTML_Core.text(article.title) ]), articleMeta(article) ]) ]);
                            };
                            var content = function (article) {
                                var renderTag = function (str) {
                                    return Halogen_HTML_Elements.li([ Conduit_Component_HTML_Utils.css("tag-default tag-pill tag-outline") ])([ Halogen_HTML_Core.text(str) ]);
                                };
                                return Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("container page") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("col-xs-12") ])([ Halogen_HTML.slot()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                    return "rawHtml";
                                }))(Data_Ord.ordUnit)(Data_Symbol.SProxy.value)(Data_Unit.unit)(Conduit_Component_RawHTML.component(dictMonadAff))({
                                    markdown: markdown
                                })(Data_Void.absurd), Halogen_HTML_Elements.ul([ Conduit_Component_HTML_Utils.css("tag-list") ])(Data_Functor.map(Data_Functor.functorArray)(renderTag)(article.tagList)), Halogen_HTML_Elements.hr_, Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("article-actions") ])([ articleMeta(article) ]), Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("row") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("col-xs-12 col-md-8 offset-md-2") ])(Data_Semigroup.append(Data_Semigroup.semigroupArray)([ Conduit_Component_HTML_Utils.maybeElem(state.currentUser)(function (profile) {
                                    return Halogen_HTML_Elements.form([ Conduit_Component_HTML_Utils.css("card comment-form"), Halogen_HTML_Events.onSubmit(function (v) {
                                        return new Data_Maybe.Just(AddComment.value);
                                    }) ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("card-block") ])([ Halogen_HTML_Elements.textarea([ Conduit_Component_HTML_Utils.css("form-control"), Halogen_HTML_Properties.placeholder("Write a comment..."), Halogen_HTML_Properties.rows(3), Halogen_HTML_Events.onValueInput(function ($760) {
                                        return Data_Maybe.Just.create(UpdateCommentText.create($760));
                                    }) ]) ]), Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("card-footer") ])([ Halogen_HTML_Elements.img([ Conduit_Component_HTML_Utils.css("comment-author-img"), Halogen_HTML_Properties.src(Conduit_Data_Avatar.toStringWithDefault(profile.image)) ]), Halogen_HTML_Elements.button([ Conduit_Component_HTML_Utils.css("btn btn-sm btn-primary"), Halogen_HTML_Properties.type_(Halogen_HTML_Core.isPropButtonType)(DOM_HTML_Indexed_ButtonType.ButtonSubmit.value) ])([ Halogen_HTML_Core.text("Post Comment") ]) ]) ]);
                                }) ])((function () {
                                    var v = Data_Lens_Fold.preview(Network_RemoteData["_Success"](Data_Lens_Internal_Forget.choiceForget(Data_Maybe_First.monoidFirst)))(state.comments);
                                    if (v instanceof Data_Maybe.Nothing) {
                                        return [ Halogen_HTML_Core.text("") ];
                                    };
                                    if (v instanceof Data_Maybe.Just) {
                                        return Data_Functor.map(Data_Functor.functorArray)(viewComment)(v.value0);
                                    };
                                    throw new Error("Failed pattern match at Conduit.Page.ViewArticle (line 228, column 23 - line 230, column 56): " + [ v.constructor.name ]);
                                })())) ]) ]) ]);
                            };
                            return Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("article-page") ])([ Conduit_Component_HTML_Header.header(state.currentUser)(new Conduit_Data_Route.ViewArticle(state.slug)), Conduit_Component_HTML_Utils.maybeElem(mbArticle)(banner), Conduit_Component_HTML_Utils.maybeElem(mbArticle)(content), Conduit_Component_HTML_Footer.footer ]);
                        };
                        var initialState = function (v) {
                            return {
                                article: Network_RemoteData.NotAsked.value,
                                comments: Network_RemoteData.NotAsked.value,
                                myComment: "",
                                currentUser: Data_Maybe.Nothing.value,
                                slug: v.slug
                            };
                        };
                        var _article = function (dictWander) {
                            var $761 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                return "article";
                            }))()()(Data_Symbol.SProxy.value)(dictWander.Strong0());
                            var $762 = Network_RemoteData["_Success"](dictWander.Choice1());
                            return function ($763) {
                                return $761($762($763));
                            };
                        };
                        var _author = function (dictWander) {
                            var $764 = _article(dictWander);
                            var $765 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                                return "author";
                            }))()()(Data_Symbol.SProxy.value)(dictWander.Strong0());
                            return function ($766) {
                                return $764($765($766));
                            };
                        };
                        var handleAction = function (v) {
                            if (v instanceof Initialize) {
                                return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Parallel.parTraverse_(Halogen_Query_HalogenM.parallelHalogenM)(Data_Foldable.foldableArray)(Halogen_Query_HalogenM.fork)([ handleAction(GetArticle.value), handleAction(GetComments.value) ]))(function ($dollar__unused) {
                                    return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Bind.bindFlipped(Halogen_Query_HalogenM.bindHalogenM)((function () {
                                        var $767 = Effect_Class.liftEffect(Halogen_Query_HalogenM.monadEffectHalogenM(dictMonadAff.MonadEffect0()));
                                        return function ($768) {
                                            return $767(Effect_Ref.read($768));
                                        };
                                    })())(Control_Monad_Reader_Class.asks(Halogen_Query_HalogenM.monadAskHalogenM(dictMonadAsk))(function (v1) {
                                        return v1.userEnv.currentUser;
                                    })))(function (mbProfile) {
                                        return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                            var $729 = {};
                                            for (var $730 in v1) {
                                                if ({}.hasOwnProperty.call(v1, $730)) {
                                                    $729[$730] = v1[$730];
                                                };
                                            };
                                            $729.currentUser = mbProfile;
                                            return $729;
                                        });
                                    });
                                });
                            };
                            if (v instanceof GetArticle) {
                                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $732 = {};
                                    for (var $733 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $733)) {
                                            $732[$733] = v1[$733];
                                        };
                                    };
                                    $732.article = Network_RemoteData.Loading.value;
                                    return $732;
                                }))(function (st) {
                                    return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Article.getArticle(Conduit_Capability_Resource_Article.manageArticleHalogenM(dictManageArticle))(st.slug))(function (article) {
                                        return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                            var $735 = {};
                                            for (var $736 in v1) {
                                                if ({}.hasOwnProperty.call(v1, $736)) {
                                                    $735[$736] = v1[$736];
                                                };
                                            };
                                            $735.article = Network_RemoteData.fromMaybe(article);
                                            return $735;
                                        });
                                    });
                                });
                            };
                            if (v instanceof GetComments) {
                                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $738 = {};
                                    for (var $739 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $739)) {
                                            $738[$739] = v1[$739];
                                        };
                                    };
                                    $738.comments = Network_RemoteData.Loading.value;
                                    return $738;
                                }))(function (st) {
                                    return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Comment.getComments(Conduit_Capability_Resource_Comment.manageCommentHalogenM(dictManageComment))(st.slug))(function (comments) {
                                        return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                            var $741 = {};
                                            for (var $742 in v1) {
                                                if ({}.hasOwnProperty.call(v1, $742)) {
                                                    $741[$742] = v1[$742];
                                                };
                                            };
                                            $741.comments = Network_RemoteData.fromMaybe(comments);
                                            return $741;
                                        });
                                    });
                                });
                            };
                            if (v instanceof AddComment) {
                                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (st) {
                                    return Control_Applicative.when(Halogen_Query_HalogenM.applicativeHalogenM)(st.myComment !== "")(Data_Foldable.for_(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Foldable.foldableMaybe)(Data_Lens_Fold.preview(Network_RemoteData["_Success"](Data_Lens_Internal_Forget.choiceForget(Data_Maybe_First.monoidFirst)))(st.article))(function (article) {
                                        return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Conduit_Capability_Resource_Comment.createComment(Conduit_Capability_Resource_Comment.manageCommentHalogenM(dictManageComment))(article.slug)(st.myComment)))(function ($dollar__unused) {
                                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Comment.getComments(Conduit_Capability_Resource_Comment.manageCommentHalogenM(dictManageComment))(st.slug))(function (comments) {
                                                return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                                    var $744 = {};
                                                    for (var $745 in v1) {
                                                        if ({}.hasOwnProperty.call(v1, $745)) {
                                                            $744[$745] = v1[$745];
                                                        };
                                                    };
                                                    $744.comments = Network_RemoteData.fromMaybe(comments);
                                                    $744.myComment = "";
                                                    return $744;
                                                });
                                            });
                                        });
                                    }));
                                });
                            };
                            if (v instanceof UpdateCommentText) {
                                return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $747 = {};
                                    for (var $748 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $748)) {
                                            $747[$748] = v1[$748];
                                        };
                                    };
                                    $747.myComment = v.value0;
                                    return $747;
                                });
                            };
                            if (v instanceof FollowAuthor) {
                                return Conduit_Component_Part_FollowButton.follow(dictManageUser)(function (dictWander) {
                                    return _author(dictWander);
                                });
                            };
                            if (v instanceof UnfollowAuthor) {
                                return Conduit_Component_Part_FollowButton.unfollow(dictManageUser)(function (dictWander) {
                                    return _author(dictWander);
                                });
                            };
                            if (v instanceof FavoriteArticle) {
                                return Conduit_Component_Part_FavoriteButton.favorite(dictManageArticle)(function (dictWander) {
                                    return _article(dictWander);
                                });
                            };
                            if (v instanceof UnfavoriteArticle) {
                                return Conduit_Component_Part_FavoriteButton.unfavorite(dictManageArticle)(function (dictWander) {
                                    return _article(dictWander);
                                });
                            };
                            if (v instanceof DeleteArticle) {
                                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (st) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Data_Foldable.for_(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Foldable.foldableMaybe)(Data_Lens_Fold.preview(Network_RemoteData["_Success"](Data_Lens_Internal_Forget.choiceForget(Data_Maybe_First.monoidFirst)))(st.article))((function () {
                                        var $769 = Conduit_Capability_Resource_Article.deleteArticle(Conduit_Capability_Resource_Article.manageArticleHalogenM(dictManageArticle));
                                        return function ($770) {
                                            return $769((function (v1) {
                                                return v1.slug;
                                            })($770));
                                        };
                                    })()))(function ($dollar__unused) {
                                        return Conduit_Capability_Navigate.navigate(Conduit_Capability_Navigate.navigateHalogenM(dictNavigate))(Conduit_Data_Route.Home.value);
                                    });
                                });
                            };
                            if (v instanceof DeleteComment) {
                                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (st) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Comment.deleteComment(Conduit_Capability_Resource_Comment.manageCommentHalogenM(dictManageComment))(st.slug)(v.value0))(function ($dollar__unused) {
                                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Comment.getComments(Conduit_Capability_Resource_Comment.manageCommentHalogenM(dictManageComment))(st.slug))(function (comments) {
                                            return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                                var $751 = {};
                                                for (var $752 in v1) {
                                                    if ({}.hasOwnProperty.call(v1, $752)) {
                                                        $751[$752] = v1[$752];
                                                    };
                                                };
                                                $751.comments = Network_RemoteData.fromMaybe(comments);
                                                return $751;
                                            });
                                        });
                                    });
                                });
                            };
                            if (v instanceof Receive) {
                                return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (st) {
                                    return Control_Applicative.when(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Eq.notEq(Slug.eqSlug)(st.slug)(v.value0.slug))(Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                        var $755 = {};
                                        for (var $756 in v1) {
                                            if ({}.hasOwnProperty.call(v1, $756)) {
                                                $755[$756] = v1[$756];
                                            };
                                        };
                                        $755.slug = v.value0.slug;
                                        return $755;
                                    }))(function ($dollar__unused) {
                                        return handleAction(Initialize.value);
                                    }));
                                });
                            };
                            throw new Error("Failed pattern match at Conduit.Page.ViewArticle (line 102, column 18 - line 156, column 32): " + [ v.constructor.name ]);
                        };
                        return Halogen_Component.mkComponent({
                            initialState: initialState,
                            render: render,
                            "eval": Halogen_Component.mkEval({
                                handleAction: handleAction,
                                handleQuery: Halogen_Component.defaultEval.handleQuery,
                                receive: function ($771) {
                                    return Data_Maybe.Just.create(Receive.create($771));
                                },
                                initialize: new Data_Maybe.Just(Initialize.value),
                                finalize: Halogen_Component.defaultEval.finalize
                            })
                        });
                    };
                };
            };
        };
    };
};
export {
    Initialize,
    GetArticle,
    GetComments,
    AddComment,
    UpdateCommentText,
    FollowAuthor,
    UnfollowAuthor,
    FavoriteArticle,
    UnfavoriteArticle,
    DeleteArticle,
    DeleteComment,
    Receive,
    component
};
