// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Nullable from "../Data.Nullable/index.js";
import * as Effect from "../Effect/index.js";
var getItem = function (s) {
    var $3068 = Data_Functor.map(Effect.functorEffect)(Data_Nullable.toMaybe);
    var $3069 = $foreign["_getItem"](s);
    return function ($3070) {
        return $3068($3069($3070));
    };
};
export {
    setItem,
    removeItem
} from "./foreign.js";
export {
    getItem
};
