// Generated by purs version 0.13.6
import * as Data_Newtype from "../Data.Newtype/index.js";
var Milliseconds = function (x) {
    return x;
};
var newtypeMilliseconds = new Data_Newtype.Newtype(function (n) {
    return n;
}, Milliseconds);
export {
    Milliseconds,
    newtypeMilliseconds
};
