// Generated by purs version 0.13.6
import * as Conduit_Component_HTML_Utils from "../Conduit.Component.HTML.Utils/index.js";
import * as Halogen_HTML_Core from "../Halogen.HTML.Core/index.js";
import * as Halogen_HTML_Elements from "../Halogen.HTML.Elements/index.js";
import * as Halogen_HTML_Properties from "../Halogen.HTML.Properties/index.js";
var footer = Halogen_HTML_Elements.footer_([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("container") ])([ Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("logo-font"), Halogen_HTML_Properties.href("/") ])([ Halogen_HTML_Core.text("conduit") ]), Halogen_HTML_Elements.span([ Conduit_Component_HTML_Utils.css("attribution") ])([ Halogen_HTML_Core.text("An interactive learning project from "), Halogen_HTML_Elements.a([ Halogen_HTML_Properties.href("https://thinkster.io") ])([ Halogen_HTML_Core.text("Thinkster") ]), Halogen_HTML_Core.text(". Code & design licensed under MIT. Implemented by "), Halogen_HTML_Elements.a([ Halogen_HTML_Properties.href("https://thomashoneyman.com") ])([ Halogen_HTML_Core.text("Thomas Honeyman") ]), Halogen_HTML_Core.text(".") ]) ]) ]);
export {
    footer
};
