// Generated by purs version 0.13.6
import * as Data_Either from "../Data.Either/index.js";
var Bottom2 = function (bottom2) {
    this.bottom2 = bottom2;
};
var bottom2Either = new Bottom2(Data_Either.Left.create);
var bottom2 = function (dict) {
    return dict.bottom2;
};
export {
    Bottom2,
    bottom2,
    bottom2Either
};
