// Generated by purs version 0.13.6
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
import * as Data_Argonaut_Decode_Struct_Cross_DecodeJsonWith from "../Data.Argonaut.Decode.Struct.Cross.DecodeJsonWith/index.js";
import * as Data_Argonaut_Decode_Struct_Override_DecodeJsonPer from "../Data.Argonaut.Decode.Struct.Override.DecodeJsonPer/index.js";
import * as Data_Argonaut_Decode_Struct_Tolerant_GDecodeJson from "../Data.Argonaut.Decode.Struct.Tolerant.GDecodeJson/index.js";
import * as Data_Argonaut_Decode_Struct_Utils from "../Data.Argonaut.Decode.Struct.Utils/index.js";
import * as Data_Operator_Top from "../Data.Operator.Top/index.js";
import * as Record_Builder from "../Record.Builder/index.js";
import * as Type_Data_RowList from "../Type.Data.RowList/index.js";
var decodeJsonWith = function (dictBind) {
    return function (dictBottom2) {
        return function (dictDecodeJsonWith) {
            return function (dictGDecodeJson) {
                return function (dictRowToList) {
                    return function (dictRowToList1) {
                        return function (dictTop1_) {
                            return function (decoderRecord) {
                                var go = function (object) {
                                    return Control_Bind.bind(dictBind)(Data_Argonaut_Decode_Struct_Tolerant_GDecodeJson.gDecodeJson(dictGDecodeJson)(Type_Data_RowList.RLProxy.value)(Type_Data_RowList.RLProxy.value)(object))(function (v) {
                                        var record2 = Record_Builder.build(v)({});
                                        return Control_Bind.bind(dictBind)(Data_Argonaut_Decode_Struct_Cross_DecodeJsonWith.decodeJsonWith(dictDecodeJsonWith)(Type_Data_RowList.RLProxy.value)(Type_Data_RowList.RLProxy.value)(decoderRecord)(object)(record2))(function (v1) {
                                            return Data_Operator_Top.top1_(dictTop1_)(Record_Builder.build(v1)(record2));
                                        });
                                    });
                                };
                                return Data_Argonaut_Decode_Struct_Utils.reportJson(dictBottom2)(go);
                            };
                        };
                    };
                };
            };
        };
    };
};
var decodeJsonPer = function (dictBind) {
    return function (dictBottom2) {
        return function (dictDecodeJsonPer) {
            return function (dictGDecodeJson) {
                return function (dictRowToList) {
                    return function (dictRowToList1) {
                        return function (dictTop1_) {
                            return function (decoderRecord) {
                                var go = function (object) {
                                    return Control_Bind.bind(dictBind)(Data_Argonaut_Decode_Struct_Tolerant_GDecodeJson.gDecodeJson(dictGDecodeJson)(Type_Data_RowList.RLProxy.value)(Type_Data_RowList.RLProxy.value)(object))(function (v) {
                                        return Control_Bind.bind(dictBind)(Data_Argonaut_Decode_Struct_Override_DecodeJsonPer.decodeJsonPer(dictDecodeJsonPer)(Type_Data_RowList.RLProxy.value)(Type_Data_RowList.RLProxy.value)(decoderRecord)(object))(function (v1) {
                                            return Data_Operator_Top.top1_(dictTop1_)(Record_Builder.build(Control_Semigroupoid.compose(Record_Builder.semigroupoidBuilder)(v1)(v))({}));
                                        });
                                    });
                                };
                                return Data_Argonaut_Decode_Struct_Utils.reportJson(dictBottom2)(go);
                            };
                        };
                    };
                };
            };
        };
    };
};
export {
    decodeJsonPer,
    decodeJsonWith
};
