// Generated by purs version 0.13.6
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Category from "../Control.Category/index.js";
import * as Control_Coroutine from "../Control.Coroutine/index.js";
import * as Control_Monad_Error_Class from "../Control.Monad.Error.Class/index.js";
import * as Control_Monad_Fork_Class from "../Control.Monad.Fork.Class/index.js";
import * as Control_Monad_Rec_Class from "../Control.Monad.Rec.Class/index.js";
import * as Control_Parallel from "../Control.Parallel/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_List from "../Data.List/index.js";
import * as Data_List_Types from "../Data.List.Types/index.js";
import * as Data_Map_Internal from "../Data.Map.Internal/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Unit from "../Data.Unit/index.js";
import * as Effect from "../Effect/index.js";
import * as Effect_Aff from "../Effect.Aff/index.js";
import * as Effect_Aff_AVar from "../Effect.Aff.AVar/index.js";
import * as Effect_Class from "../Effect.Class/index.js";
import * as Effect_Console from "../Effect.Console/index.js";
import * as Effect_Exception from "../Effect.Exception/index.js";
import * as Effect_Ref from "../Effect.Ref/index.js";
import * as Halogen_Aff_Driver_Eval from "../Halogen.Aff.Driver.Eval/index.js";
import * as Halogen_Aff_Driver_State from "../Halogen.Aff.Driver.State/index.js";
import * as Halogen_Component from "../Halogen.Component/index.js";
import * as Halogen_Data_Slot from "../Halogen.Data.Slot/index.js";
import * as Halogen_Query_EventSource from "../Halogen.Query.EventSource/index.js";
import * as Halogen_Query_HalogenQ from "../Halogen.Query.HalogenQ/index.js";
import * as Halogen_Query_Input from "../Halogen.Query.Input/index.js";
var newLifecycleHandlers = Effect_Ref["new"]({
    initializers: Data_List_Types.Nil.value,
    finalizers: Data_List_Types.Nil.value
});
var handleAff = Effect_Aff.runAff_(Data_Either.either(Effect_Exception.throwException)(Data_Function["const"](Control_Applicative.pure(Effect.applicativeEffect)(Data_Unit.unit))));
var handlePending = function (ref) {
    return function __do() {
        var queue = Effect_Ref.read(ref)();
        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(Data_Maybe.Nothing.value)(ref))(function ($dollar__unused) {
            return Data_Foldable.for_(Effect.applicativeEffect)(Data_Foldable.foldableMaybe)(queue)((function () {
                var $2208 = Data_Foldable.traverse_(Effect_Aff.applicativeAff)(Data_List_Types.foldableList)(Control_Monad_Fork_Class.fork(Control_Monad_Fork_Class.monadForkAff));
                return function ($2209) {
                    return handleAff($2208(Data_List.reverse($2209)));
                };
            })());
        })();
    };
};
var cleanupSubscriptionsAndForks = function (v) {
    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Bind.bindFlipped(Effect.bindEffect)(Data_Foldable.traverse_(Effect.applicativeEffect)(Data_Foldable.foldableMaybe)((function () {
        var $2210 = Data_Foldable.traverse_(Effect_Aff.applicativeAff)(Data_Map_Internal.foldableMap)((function () {
            var $2212 = Control_Monad_Fork_Class.fork(Control_Monad_Fork_Class.monadForkAff);
            return function ($2213) {
                return $2212(Halogen_Query_EventSource.finalize($2213));
            };
        })());
        return function ($2211) {
            return handleAff($2210($2211));
        };
    })()))(Effect_Ref.read(v.subscriptions)))(function ($dollar__unused) {
        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(Data_Maybe.Nothing.value)(v.subscriptions))(function ($dollar__unused) {
            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Bind.bindFlipped(Effect.bindEffect)(Data_Foldable.traverse_(Effect.applicativeEffect)(Data_Map_Internal.foldableMap)((function () {
                var $2214 = Effect_Aff.killFiber(Effect_Exception.error("finalized"));
                return function ($2215) {
                    return handleAff($2214($2215));
                };
            })()))(Effect_Ref.read(v.forks)))(function ($dollar__unused) {
                return Effect_Ref.write(Data_Map_Internal.empty)(v.forks);
            });
        });
    });
};
var runUI = function (renderSpec) {
    return function (component) {
        return function (i) {
            var subscribe = function (fresh) {
                return function (ref) {
                    return function (consumer) {
                        return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Aff_AVar.empty)(function (inputVar) {
                            return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(function __do() {
                                var listenerId = Effect_Ref.read(fresh)();
                                return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.modify_(function (v) {
                                    return v + 1 | 0;
                                })(fresh))(function ($dollar__unused) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.modify_(Data_Map_Internal.insert(Data_Ord.ordInt)(listenerId)(inputVar))(ref))(function ($dollar__unused) {
                                        return Control_Applicative.pure(Effect.applicativeEffect)(listenerId);
                                    });
                                })();
                            }))(function (listenerId) {
                                var producer = Control_Coroutine.producer(Effect_Aff.monadAff)(Data_Functor.map(Effect_Aff.functorAff)(Data_Either.either(Data_Function["const"](new Data_Either.Right(Data_Unit.unit)))(Data_Either.Left.create))(Control_Monad_Error_Class["try"](Effect_Aff.monadErrorAff)(Effect_Aff_AVar.take(inputVar))));
                                return Data_Functor["void"](Effect_Aff.functorAff)(Control_Monad_Fork_Class.fork(Control_Monad_Fork_Class.monadForkAff)(Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff)(Control_Coroutine.runProcess(Effect_Aff.monadRecAff)(Control_Coroutine.connect(Effect_Aff.monadRecAff)(Effect_Aff.parallelAff)(producer)(consumer)))(function ($dollar__unused) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Effect_Ref.modify_(Data_Map_Internal["delete"](Data_Ord.ordInt)(listenerId))(ref)))(function ($dollar__unused) {
                                        return Effect_Aff_AVar.kill(Effect_Exception.error("ended"))(inputVar);
                                    });
                                })));
                            });
                        });
                    };
                };
            };
            var rootHandler = function (ref) {
                return function (message) {
                    return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Effect_Ref.read(ref)))(function (listeners) {
                        return Data_Foldable.traverse_(Effect_Aff.applicativeAff)(Data_Map_Internal.foldableMap)(Control_Monad_Fork_Class.fork(Control_Monad_Fork_Class.monadForkAff))(Data_Functor.map(Data_Map_Internal.functorMap)(Effect_Aff_AVar.put(message))(listeners));
                    });
                };
            };
            var squashChildInitializers = function (lchs) {
                return function (preInits) {
                    return Halogen_Aff_Driver_State.unDriverStateX(function (st) {
                        var parentInitializer = Halogen_Aff_Driver_Eval.evalM(render)(st.selfRef)(st["component"]["eval"](new Halogen_Query_HalogenQ.Initialize(Data_Unit.unit)));
                        return Effect_Ref.modify_(function (handlers) {
                            return {
                                initializers: new Data_List_Types.Cons(Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff)(Control_Parallel.parSequence_(Effect_Aff.parallelAff)(Data_List_Types.foldableList)(Data_List.reverse(handlers.initializers)))(function ($dollar__unused) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff)(parentInitializer)(function ($dollar__unused) {
                                        return Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(handlePending(st.pendingQueries))(function ($dollar__unused) {
                                            return handlePending(st.pendingOuts);
                                        }));
                                    });
                                }), preInits),
                                finalizers: handlers.finalizers
                            };
                        })(lchs);
                    });
                };
            };
            var runComponent = function (lchs) {
                return function (handler) {
                    return function (j) {
                        return Halogen_Component.unComponent(function (c) {
                            return function __do() {
                                var lchs$prime = newLifecycleHandlers();
                                var $$var = Halogen_Aff_Driver_State.initDriverState(c)(j)(handler)(lchs$prime)();
                                var pre = Effect_Ref.read(lchs)();
                                return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write({
                                    initializers: Data_List_Types.Nil.value,
                                    finalizers: pre.finalizers
                                })(lchs))(function ($dollar__unused) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Bind.bindFlipped(Effect.bindEffect)(Halogen_Aff_Driver_State.unDriverStateX((function () {
                                        var $2216 = render(lchs);
                                        return function ($2217) {
                                            return $2216((function (v) {
                                                return v.selfRef;
                                            })($2217));
                                        };
                                    })()))(Effect_Ref.read($$var)))(function ($dollar__unused) {
                                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Bind.bindFlipped(Effect.bindEffect)(squashChildInitializers(lchs)(pre.initializers))(Effect_Ref.read($$var)))(function ($dollar__unused) {
                                            return Control_Applicative.pure(Effect.applicativeEffect)($$var);
                                        });
                                    });
                                })();
                            };
                        });
                    };
                };
            };
            var renderChild = function (lchs) {
                return function (handler) {
                    return function (childrenInRef) {
                        return function (childrenOutRef) {
                            return Halogen_Component.unComponentSlot(function (slot) {
                                return function __do() {
                                    var childrenIn = Data_Functor.map(Effect.functorEffect)(slot.pop)(Effect_Ref.read(childrenInRef))();
                                    var $$var = (function () {
                                        if (childrenIn instanceof Data_Maybe.Just) {
                                            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(childrenIn.value0.value1)(childrenInRef))(function ($dollar__unused) {
                                                return function __do() {
                                                    var dsx = Effect_Ref.read(childrenIn.value0.value0)();
                                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Halogen_Aff_Driver_State.unDriverStateX(function (st) {
                                                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Data_Function.flip(Effect_Ref.write)(st.handlerRef)((function () {
                                                            var $2218 = Data_Maybe.maybe(Control_Applicative.pure(Effect_Aff.applicativeAff)(Data_Unit.unit))(handler);
                                                            return function ($2219) {
                                                                return $2218(slot.output($2219));
                                                            };
                                                        })()))(function ($dollar__unused) {
                                                            return handleAff(Halogen_Aff_Driver_Eval.evalM(render)(st.selfRef)(st["component"]["eval"](slot.input)));
                                                        });
                                                    })(dsx))(function ($dollar__unused) {
                                                        return Control_Applicative.pure(Effect.applicativeEffect)(childrenIn.value0.value0);
                                                    })();
                                                };
                                            })();
                                        };
                                        if (childrenIn instanceof Data_Maybe.Nothing) {
                                            if (slot.input instanceof Halogen_Query_HalogenQ.Receive) {
                                                return runComponent(lchs)((function () {
                                                    var $2220 = Data_Maybe.maybe(Control_Applicative.pure(Effect_Aff.applicativeAff)(Data_Unit.unit))(handler);
                                                    return function ($2221) {
                                                        return $2220(slot.output($2221));
                                                    };
                                                })())(slot.input.value0)(slot.component)();
                                            };
                                            return Effect_Exception["throw"]("Halogen internal error: slot input was not a Receive query")();
                                        };
                                        throw new Error("Failed pattern match at Halogen.Aff.Driver (line 236, column 14 - line 249, column 81): " + [ childrenIn.constructor.name ]);
                                    })();
                                    var isDuplicate = Data_Functor.map(Effect.functorEffect)(function ($2222) {
                                        return Data_Maybe.isJust(slot.get($2222));
                                    })(Effect_Ref.read(childrenOutRef))();
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Applicative.when(Effect.applicativeEffect)(isDuplicate)(Effect_Console.warn("Halogen: Duplicate slot address was detected during rendering, unexpected results may occur")))(function ($dollar__unused) {
                                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.modify_(slot.set($$var))(childrenOutRef))(function ($dollar__unused) {
                                            return Control_Bind.bind(Effect.bindEffect)(Effect_Ref.read($$var))(Halogen_Aff_Driver_State.renderStateX(Effect.functorEffect)(function (v) {
                                                if (v instanceof Data_Maybe.Nothing) {
                                                    return Effect_Exception["throw"]("Halogen internal error: child was not initialized in renderChild");
                                                };
                                                if (v instanceof Data_Maybe.Just) {
                                                    return Control_Applicative.pure(Effect.applicativeEffect)(renderSpec.renderChild(v.value0));
                                                };
                                                throw new Error("Failed pattern match at Halogen.Aff.Driver (line 254, column 37 - line 256, column 50): " + [ v.constructor.name ]);
                                            }));
                                        });
                                    })();
                                };
                            });
                        };
                    };
                };
            };
            var render = function (lchs) {
                return function ($$var) {
                    return function __do() {
                        var v = Effect_Ref.read($$var)();
                        var shouldProcessHandlers = Data_Functor.map(Effect.functorEffect)(Data_Maybe.isNothing)(Effect_Ref.read(v.pendingHandlers))();
                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Applicative.when(Effect.applicativeEffect)(shouldProcessHandlers)(Effect_Ref.write(new Data_Maybe.Just(Data_List_Types.Nil.value))(v.pendingHandlers)))(function ($dollar__unused) {
                            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(Halogen_Data_Slot.empty)(v.childrenOut))(function ($dollar__unused) {
                                return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(v.children)(v.childrenIn))(function ($dollar__unused) {
                                    var selfRef = Control_Category.identity(Control_Category.categoryFn)(v.selfRef);
                                    var pendingQueries = Control_Category.identity(Control_Category.categoryFn)(v.pendingQueries);
                                    var pendingHandlers = Control_Category.identity(Control_Category.categoryFn)(v.pendingHandlers);
                                    var handler = (function () {
                                        var $2223 = Halogen_Aff_Driver_Eval.queueOrRun(pendingHandlers);
                                        var $2224 = Data_Functor["void"](Effect_Aff.functorAff);
                                        var $2225 = Halogen_Aff_Driver_Eval.evalF(render)(selfRef);
                                        return function ($2226) {
                                            return $2223($2224($2225($2226)));
                                        };
                                    })();
                                    var childHandler = (function () {
                                        var $2227 = Halogen_Aff_Driver_Eval.queueOrRun(pendingQueries);
                                        return function ($2228) {
                                            return $2227(handler(Halogen_Query_Input.Action.create($2228)));
                                        };
                                    })();
                                    return function __do() {
                                        var rendering = renderSpec.render(function ($2229) {
                                            return handleAff(handler($2229));
                                        })(renderChild(lchs)(childHandler)(v.childrenIn)(v.childrenOut))(v.component.render(v.state))(v.rendering)();
                                        var children = Effect_Ref.read(v.childrenOut)();
                                        var childrenIn = Effect_Ref.read(v.childrenIn)();
                                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Halogen_Data_Slot.foreachSlot(Effect.applicativeEffect)(childrenIn)(function (v1) {
                                            return function __do() {
                                                var childDS = Effect_Ref.read(v1)();
                                                return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Halogen_Aff_Driver_State.renderStateX_(Effect.applicativeEffect)(renderSpec.removeChild)(childDS))(function ($dollar__unused) {
                                                    return finalize(lchs)(childDS);
                                                })();
                                            };
                                        }))(function ($dollar__unused) {
                                            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Data_Function.flip(Effect_Ref.modify_)(v.selfRef)(Halogen_Aff_Driver_State.mapDriverState(function (ds$prime) {
                                                return {
                                                    component: ds$prime.component,
                                                    state: ds$prime.state,
                                                    refs: ds$prime.refs,
                                                    children: children,
                                                    childrenIn: ds$prime.childrenIn,
                                                    childrenOut: ds$prime.childrenOut,
                                                    selfRef: ds$prime.selfRef,
                                                    handlerRef: ds$prime.handlerRef,
                                                    pendingQueries: ds$prime.pendingQueries,
                                                    pendingOuts: ds$prime.pendingOuts,
                                                    pendingHandlers: ds$prime.pendingHandlers,
                                                    rendering: new Data_Maybe.Just(rendering),
                                                    fresh: ds$prime.fresh,
                                                    subscriptions: ds$prime.subscriptions,
                                                    forks: ds$prime.forks,
                                                    lifecycleHandlers: ds$prime.lifecycleHandlers
                                                };
                                            })))(function ($dollar__unused) {
                                                return Control_Applicative.when(Effect.applicativeEffect)(shouldProcessHandlers)(Data_Function.flip(Control_Monad_Rec_Class.tailRecM(Control_Monad_Rec_Class.monadRecEffect))(Data_Unit.unit)(function (v1) {
                                                    return function __do() {
                                                        var handlers = Effect_Ref.read(pendingHandlers)();
                                                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(new Data_Maybe.Just(Data_List_Types.Nil.value))(pendingHandlers))(function ($dollar__unused) {
                                                            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Data_Foldable.traverse_(Effect.applicativeEffect)(Data_Foldable.foldableMaybe)((function () {
                                                                var $2230 = Data_Foldable.traverse_(Effect_Aff.applicativeAff)(Data_List_Types.foldableList)(Control_Monad_Fork_Class.fork(Control_Monad_Fork_Class.monadForkAff));
                                                                return function ($2231) {
                                                                    return handleAff($2230(Data_List.reverse($2231)));
                                                                };
                                                            })())(handlers))(function ($dollar__unused) {
                                                                return function __do() {
                                                                    var mmore = Effect_Ref.read(pendingHandlers)();
                                                                    var $2204 = Data_Maybe.maybe(false)(Data_List["null"])(mmore);
                                                                    if ($2204) {
                                                                        return Data_Functor.voidLeft(Effect.functorEffect)(Effect_Ref.write(Data_Maybe.Nothing.value)(pendingHandlers))(new Control_Monad_Rec_Class.Done(Data_Unit.unit))();
                                                                    };
                                                                    return new Control_Monad_Rec_Class.Loop(Data_Unit.unit);
                                                                };
                                                            });
                                                        })();
                                                    };
                                                }));
                                            });
                                        })();
                                    };
                                });
                            });
                        })();
                    };
                };
            };
            var finalize = function (lchs) {
                return Halogen_Aff_Driver_State.unDriverStateX(function (st) {
                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(cleanupSubscriptionsAndForks(st))(function ($dollar__unused) {
                        var f = Halogen_Aff_Driver_Eval.evalM(render)(st.selfRef)(st["component"]["eval"](new Halogen_Query_HalogenQ.Finalize(Data_Unit.unit)));
                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.modify_(function (handlers) {
                            return {
                                initializers: handlers.initializers,
                                finalizers: new Data_List_Types.Cons(f, handlers.finalizers)
                            };
                        })(lchs))(function ($dollar__unused) {
                            return Halogen_Data_Slot.foreachSlot(Effect.applicativeEffect)(st.children)(function (v) {
                                return function __do() {
                                    var dsx = Effect_Ref.read(v)();
                                    return finalize(lchs)(dsx)();
                                };
                            });
                        });
                    });
                });
            };
            var evalDriver = function (disposed) {
                return function (ref) {
                    return function (q) {
                        return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Effect_Ref.read(disposed)))(function (v) {
                            if (v) {
                                return Control_Applicative.pure(Effect_Aff.applicativeAff)(Data_Maybe.Nothing.value);
                            };
                            return Halogen_Aff_Driver_Eval.evalQ(render)(ref)(q);
                        });
                    };
                };
            };
            var dispose = function (disposed) {
                return function (lchs) {
                    return function (dsx) {
                        return function (subsRef) {
                            return Halogen_Aff_Driver_Eval.handleLifecycle(lchs)(function __do() {
                                var v = Effect_Ref.read(disposed)();
                                if (v) {
                                    return Data_Unit.unit;
                                };
                                return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Effect_Ref.write(true)(disposed))(function ($dollar__unused) {
                                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Control_Bind.bindFlipped(Effect.bindEffect)(Data_Foldable.traverse_(Effect.applicativeEffect)(Data_Map_Internal.foldableMap)((function () {
                                        var $2232 = Effect_Aff_AVar.kill(Effect_Exception.error("disposed"));
                                        return function ($2233) {
                                            return Effect_Aff.launchAff_($2232($2233));
                                        };
                                    })()))(Effect_Ref.read(subsRef)))(function ($dollar__unused) {
                                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(finalize(lchs)(dsx))(function ($dollar__unused) {
                                            return Halogen_Aff_Driver_State.unDriverStateX((function () {
                                                var $2234 = Data_Foldable.traverse_(Effect.applicativeEffect)(Data_Foldable.foldableMaybe)(renderSpec.dispose);
                                                return function ($2235) {
                                                    return $2234((function (v1) {
                                                        return v1.rendering;
                                                    })($2235));
                                                };
                                            })())(dsx);
                                        });
                                    });
                                })();
                            });
                        };
                    };
                };
            };
            return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(newLifecycleHandlers))(function (lchs) {
                return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Effect_Ref["new"](0)))(function (fresh) {
                    return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Effect_Ref["new"](false)))(function (disposed) {
                        return Halogen_Aff_Driver_Eval.handleLifecycle(lchs)(function __do() {
                            var listeners = Effect_Ref["new"](Data_Map_Internal.empty)();
                            var dsx = Control_Bind.bindFlipped(Effect.bindEffect)(Effect_Ref.read)(runComponent(lchs)(rootHandler(listeners))(i)(component))();
                            return Halogen_Aff_Driver_State.unDriverStateX(function (st) {
                                return Control_Applicative.pure(Effect.applicativeEffect)({
                                    query: evalDriver(disposed)(st.selfRef),
                                    subscribe: subscribe(fresh)(listeners),
                                    dispose: dispose(disposed)(lchs)(dsx)(listeners)
                                });
                            })(dsx)();
                        });
                    });
                });
            });
        };
    };
};
export {
    runUI
};
