// Generated by purs version 0.13.6
import * as Data_Argonaut_Decode_Class from "../Data.Argonaut.Decode.Class/index.js";
import * as Data_Argonaut_Encode_Class from "../Data.Argonaut.Encode.Class/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
var Username = function (x) {
    return x;
};
var toString = function (v) {
    return v;
};
var parse = function (v) {
    if (v === "") {
        return Data_Maybe.Nothing.value;
    };
    return new Data_Maybe.Just(v);
};
var eqUsername = new Data_Eq.Eq(function (x) {
    return function (y) {
        return x === y;
    };
});
var encodeJsonUsername = Data_Argonaut_Encode_Class.encodeJsonJString;
var decodeJsonUsername = Data_Argonaut_Decode_Class.decodeJsonString;
export {
    parse,
    toString,
    eqUsername,
    encodeJsonUsername,
    decodeJsonUsername
};
