// Generated by purs version 0.13.6
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Monad_Rec_Class from "../Control.Monad.Rec.Class/index.js";
import * as Effect_Aff from "../Effect.Aff/index.js";
import * as Effect_Aff_Bus from "../Effect.Aff.Bus/index.js";
import * as Effect_Exception from "../Effect.Exception/index.js";
import * as Halogen_Query_EventSource from "../Halogen.Query.EventSource/index.js";
var busEventSource = function (dictMonadAff) {
    return function (bus) {
        return Halogen_Query_EventSource.affEventSource(dictMonadAff)(function (emitter) {
            return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Aff.forkAff(Control_Monad_Rec_Class.forever(Effect_Aff.monadRecAff)(Control_Bind.bindFlipped(Effect_Aff.bindAff)(Halogen_Query_EventSource.emit(emitter))(Effect_Aff_Bus.read(bus)))))(function (fiber) {
                return Control_Applicative.pure(Effect_Aff.applicativeAff)(Effect_Aff.killFiber(Effect_Exception.error("Event source closed"))(fiber));
            });
        });
    };
};
export {
    busEventSource
};
