// Generated by purs version 0.13.6
import * as Data_Functor_Variant from "../Data.Functor.Variant/index.js";
import * as Data_Symbol from "../Data.Symbol/index.js";
import * as Formless_Types_Component from "../Formless.Types.Component/index.js";
import * as Halogen_Query from "../Halogen.Query/index.js";
var injQuery = function (dictFunctor) {
    return Data_Functor_Variant.inj()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "userQuery";
    }))(dictFunctor)(Data_Symbol.SProxy.value);
};
var asQuery = (function () {
    var $2151 = Data_Functor_Variant.inj()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "query";
    }))(Formless_Types_Component.functorQueryF)(Data_Symbol.SProxy.value);
    return function ($2152) {
        return $2151(Halogen_Query.tell(Formless_Types_Component.AsQuery.create($2152)));
    };
})();
export {
    injQuery,
    asQuery
};
