// Generated by purs version 0.13.8
"use strict";
var Data_Functor_Variant = require("../Data.Functor.Variant/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Formless_Types_Component = require("../Formless.Types.Component/index.js");
var Halogen_Query = require("../Halogen.Query/index.js");
var injQuery = function (dictFunctor) {
    return Data_Functor_Variant.inj()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "userQuery";
    }))(dictFunctor)(Data_Symbol.SProxy.value);
};
var asQuery = (function () {
    var $2147 = Data_Functor_Variant.inj()(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "query";
    }))(Formless_Types_Component.functorQueryF)(Data_Symbol.SProxy.value);
    return function ($2148) {
        return $2147(Halogen_Query.tell(Formless_Types_Component.AsQuery.create($2148)));
    };
})();
module.exports = {
    injQuery: injQuery,
    asQuery: asQuery
};
