// Generated by purs version 0.13.6
import * as Data_Newtype from "../Data.Newtype/index.js";
var MediaType = function (x) {
    return x;
};
var newtypeMediaType = new Data_Newtype.Newtype(function (n) {
    return n;
}, MediaType);
export {
    MediaType,
    newtypeMediaType
};
