// Generated by purs version 0.13.8
"use strict";
var Data_Symbol = require("../Data.Symbol/index.js");
var Record_Builder = require("../Record.Builder/index.js");
var RInsert = function (rinsert) {
    this.rinsert = rinsert;
};
var rinsertBuilder = function (dictIsSymbol) {
    return function (dictSProxying) {
        return new RInsert(function (dictCons) {
            return function (dictLacks) {
                return function (v) {
                    return function (v1) {
                        return function (v2) {
                            return Record_Builder.insert()()(dictIsSymbol)(Data_Symbol.SProxy.value);
                        };
                    };
                };
            };
        });
    };
};
var rinsert = function (dict) {
    return dict.rinsert;
};
module.exports = {
    RInsert: RInsert,
    rinsert: rinsert,
    rinsertBuilder: rinsertBuilder
};
