// Generated by purs version 0.13.6
import * as Data_Symbol from "../Data.Symbol/index.js";
import * as Record_Builder from "../Record.Builder/index.js";
var RInsert = function (rinsert) {
    this.rinsert = rinsert;
};
var rinsertBuilder = function (dictIsSymbol) {
    return function (dictSProxying) {
        return new RInsert(function (dictCons) {
            return function (dictLacks) {
                return function (v) {
                    return function (v1) {
                        return function (v2) {
                            return Record_Builder.insert()()(dictIsSymbol)(Data_Symbol.SProxy.value);
                        };
                    };
                };
            };
        });
    };
};
var rinsert = function (dict) {
    return dict.rinsert;
};
export {
    RInsert,
    rinsert,
    rinsertBuilder
};
