// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Effect from "../Effect/index.js";
import * as Unsafe_Coerce from "../Unsafe.Coerce/index.js";
import * as Web_HTML_HTMLDocument_ReadyState from "../Web.HTML.HTMLDocument.ReadyState/index.js";
var toParentNode = Unsafe_Coerce.unsafeCoerce;
var toDocument = Unsafe_Coerce.unsafeCoerce;
var readyState = (function () {
    var $3063 = Data_Functor.map(Effect.functorEffect)((function () {
        var $3065 = Data_Maybe.fromMaybe(Web_HTML_HTMLDocument_ReadyState.Loading.value);
        return function ($3066) {
            return $3065(Web_HTML_HTMLDocument_ReadyState.parse($3066));
        };
    })());
    return function ($3064) {
        return $3063($foreign["_readyState"]($3064));
    };
})();
export {
    toDocument,
    toParentNode,
    readyState
};
