// Generated by purs version 0.13.6
import * as Control_Bind from "../Control.Bind/index.js";
import * as Data_Argonaut_Decode_Class from "../Data.Argonaut.Decode.Class/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Formatter_DateTime from "../Data.Formatter.DateTime/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_List from "../Data.List/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_PreciseDateTime from "../Data.PreciseDateTime/index.js";
import * as Data_RFC3339String from "../Data.RFC3339String/index.js";
var PreciseDateTime = function (x) {
    return x;
};
var newtypePreciseDateTime = new Data_Newtype.Newtype(function (n) {
    return n;
}, PreciseDateTime);
var toDateTime = (function () {
    var $404 = Data_Newtype.unwrap(newtypePreciseDateTime);
    return function ($405) {
        return Data_PreciseDateTime.toDateTimeLossy($404($405));
    };
})();
var toDisplayMonthDayYear = (function () {
    var dateFormatter = Data_List.fromFoldable(Data_Foldable.foldableArray)([ Data_Formatter_DateTime.MonthFull.value, new Data_Formatter_DateTime.Placeholder(" "), Data_Formatter_DateTime.DayOfMonth.value, new Data_Formatter_DateTime.Placeholder(", "), Data_Formatter_DateTime.YearFull.value ]);
    var $406 = Data_Formatter_DateTime.format(dateFormatter);
    return function ($407) {
        return $406(toDateTime($407));
    };
})();
var toDisplayWeekName = (function () {
    var dateFormatter = Data_List.fromFoldable(Data_Foldable.foldableArray)([ Data_Formatter_DateTime.DayOfWeekNameShort.value, new Data_Formatter_DateTime.Placeholder(" "), Data_Formatter_DateTime.MonthShort.value, new Data_Formatter_DateTime.Placeholder(" "), Data_Formatter_DateTime.DayOfMonth.value, new Data_Formatter_DateTime.Placeholder(", "), Data_Formatter_DateTime.YearFull.value ]);
    var $408 = Data_Formatter_DateTime.format(dateFormatter);
    return function ($409) {
        return $408(toDateTime($409));
    };
})();
var fromString = (function () {
    var $410 = Data_Functor.map(Data_Either.functorEither)(PreciseDateTime);
    var $411 = Data_Either.note("Could not parse RFC339 string");
    return function ($412) {
        return $410($411(Data_PreciseDateTime.fromRFC3339String(Data_RFC3339String.RFC3339String($412))));
    };
})();
var decodeJsonPreciseDateTime = new Data_Argonaut_Decode_Class.DecodeJson(Control_Bind.composeKleisliFlipped(Data_Either.bindEither)(fromString)(Data_Argonaut_Decode_Class.decodeJson(Data_Argonaut_Decode_Class.decodeJsonString)));
export {
    PreciseDateTime,
    fromString,
    toDateTime,
    toDisplayWeekName,
    toDisplayMonthDayYear,
    newtypePreciseDateTime,
    decodeJsonPreciseDateTime
};
