// Generated by purs version 0.13.6
import * as Data_Symbol from "../Data.Symbol/index.js";
var SProxying = function (sProxy) {
    this.sProxy = sProxy;
};
var sProxyingSProxy = new SProxying(Data_Symbol.SProxy.value);
export {
    SProxying,
    sProxyingSProxy
};
