// Generated by purs version 0.13.6
import * as Data_Boolean from "../Data.Boolean/index.js";
import * as Data_Bounded from "../Data.Bounded/index.js";
import * as Data_Enum from "../Data.Enum/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
var Nanosecond = function (x) {
    return x;
};
var ordNanosecond = Data_Ord.ordInt;
var boundedNanosecond = new Data_Bounded.Bounded(function ($dollar__unused) {
    return ordNanosecond;
}, 0, 999999);
var boundedEnumNanosecond = new Data_Enum.BoundedEnum(function ($dollar__unused) {
    return boundedNanosecond;
}, function ($dollar__unused) {
    return enumNanosecond;
}, 1000000, function (v) {
    return v;
}, function (n) {
    if (n >= 0 && n <= 999999) {
        return new Data_Maybe.Just(n);
    };
    if (Data_Boolean.otherwise) {
        return Data_Maybe.Nothing.value;
    };
    throw new Error("Failed pattern match at Data.PreciseDate.Component (line 35, column 1 - line 40, column 30): " + [ n.constructor.name ]);
});
var enumNanosecond = new Data_Enum.Enum(function ($dollar__unused) {
    return ordNanosecond;
}, (function () {
    var $1805 = Data_Enum.toEnum(boundedEnumNanosecond);
    var $1806 = Data_Enum.fromEnum(boundedEnumNanosecond);
    return function ($1807) {
        return $1805((function (v) {
            return v - 1 | 0;
        })($1806($1807)));
    };
})(), (function () {
    var $1808 = Data_Enum.toEnum(boundedEnumNanosecond);
    var $1809 = Data_Enum.fromEnum(boundedEnumNanosecond);
    return function ($1810) {
        return $1808((function (v) {
            return v + 1 | 0;
        })($1809($1810)));
    };
})());
export {
    Nanosecond,
    ordNanosecond,
    boundedNanosecond,
    enumNanosecond,
    boundedEnumNanosecond
};
