// Generated by purs version 0.13.8
"use strict";
var Dev = (function () {
    function Dev() {

    };
    Dev.value = new Dev();
    return Dev;
})();
var Prod = (function () {
    function Prod() {

    };
    Prod.value = new Prod();
    return Prod;
})();
module.exports = {
    Dev: Dev,
    Prod: Prod
};
