// Generated by purs version 0.13.6
import * as Control_Apply from "../Control.Apply/index.js";
import * as Data_Bifunctor from "../Data.Bifunctor/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Identity from "../Data.Identity/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Text_Parsing_Parser from "../Text.Parsing.Parser/index.js";
import * as Text_Parsing_Parser_Combinators from "../Text.Parsing.Parser.Combinators/index.js";
import * as Text_Parsing_Parser_String from "../Text.Parsing.Parser.String/index.js";
var printPosition = function (v) {
    return "(line " + (Data_Show.show(Data_Show.showInt)(v.line) + (", col " + (Data_Show.show(Data_Show.showInt)(v.column) + ")")));
};
var printError = function (err) {
    return Text_Parsing_Parser.parseErrorMessage(err) + (" " + printPosition(Text_Parsing_Parser.parseErrorPosition(err)));
};
var runP = function (dictStringLike) {
    return function (p) {
        return function (s) {
            return Data_Bifunctor.lmap(Data_Either.bifunctorEither)(printError)(Text_Parsing_Parser.runParser(s)(Control_Apply.applyFirst(Text_Parsing_Parser.applyParserT(Data_Identity.monadIdentity))(p)(Text_Parsing_Parser_String.eof(dictStringLike)(Data_Identity.monadIdentity))));
        };
    };
};
var oneOfAs = function (dictFunctor) {
    return function (dictFoldable) {
        return function (dictMonad) {
            return function (p) {
                return function (xs) {
                    return Text_Parsing_Parser_Combinators.choice(dictFoldable)(dictMonad)(Data_Functor.map(dictFunctor)(function (v) {
                        return Data_Functor.voidLeft(Text_Parsing_Parser.functorParserT(((dictMonad.Bind1()).Apply0()).Functor0()))(p(v.value0))(v.value1);
                    })(xs));
                };
            };
        };
    };
};
export {
    oneOfAs,
    runP
};
