// Generated by purs version 0.13.8
"use strict";
var $foreign = require("./foreign.js");
var RawHTML = function (x) {
    return x;
};
var marked = function (str) {
    return $foreign.markedImpl(str);
};
module.exports = {
    marked: marked
};
