// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Nullable from "../Data.Nullable/index.js";
import * as Effect from "../Effect/index.js";
var QuerySelector = function (x) {
    return x;
};
var querySelector = function (qs) {
    var $3059 = Data_Functor.map(Effect.functorEffect)(Data_Nullable.toMaybe);
    var $3060 = $foreign["_querySelector"](qs);
    return function ($3061) {
        return $3059($3060($3061));
    };
};
export {
    QuerySelector,
    querySelector
};
