// Generated by purs version 0.13.8
"use strict";
var Conduit_Api_Endpoint = require("../Conduit.Api.Endpoint/index.js");
var Conduit_Capability_Resource_Article = require("../Conduit.Capability.Resource.Article/index.js");
var Conduit_Capability_Resource_User = require("../Conduit.Capability.Resource.User/index.js");
var Conduit_Component_HTML_ArticleList = require("../Conduit.Component.HTML.ArticleList/index.js");
var Conduit_Component_HTML_Footer = require("../Conduit.Component.HTML.Footer/index.js");
var Conduit_Component_HTML_Header = require("../Conduit.Component.HTML.Header/index.js");
var Conduit_Component_HTML_Utils = require("../Conduit.Component.HTML.Utils/index.js");
var Conduit_Component_Part_FavoriteButton = require("../Conduit.Component.Part.FavoriteButton/index.js");
var Conduit_Component_Part_FollowButton = require("../Conduit.Component.Part.FollowButton/index.js");
var Conduit_Data_Avatar = require("../Conduit.Data.Avatar/index.js");
var Conduit_Data_Route = require("../Conduit.Data.Route/index.js");
var Conduit_Data_Username = require("../Conduit.Data.Username/index.js");
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Control_Monad_Reader_Class = require("../Control.Monad.Reader.Class/index.js");
var Control_Monad_State_Class = require("../Control.Monad.State.Class/index.js");
var Data_Eq = require("../Data.Eq/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Lens_Index = require("../Data.Lens.Index/index.js");
var Data_Lens_Record = require("../Data.Lens.Record/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Effect_Class = require("../Effect.Class/index.js");
var Effect_Ref = require("../Effect.Ref/index.js");
var Halogen_Component = require("../Halogen.Component/index.js");
var Halogen_HTML_Core = require("../Halogen.HTML.Core/index.js");
var Halogen_HTML_Elements = require("../Halogen.HTML.Elements/index.js");
var Halogen_HTML_Properties = require("../Halogen.HTML.Properties/index.js");
var Halogen_Query_HalogenM = require("../Halogen.Query.HalogenM/index.js");
var Network_RemoteData = require("../Network.RemoteData/index.js");
var Web_Event_Event = require("../Web.Event.Event/index.js");
var Web_UIEvent_MouseEvent = require("../Web.UIEvent.MouseEvent/index.js");
var ArticlesTab = (function () {
    function ArticlesTab() {

    };
    ArticlesTab.value = new ArticlesTab();
    return ArticlesTab;
})();
var FavoritesTab = (function () {
    function FavoritesTab() {

    };
    FavoritesTab.value = new FavoritesTab();
    return FavoritesTab;
})();
var Initialize = (function () {
    function Initialize() {

    };
    Initialize.value = new Initialize();
    return Initialize;
})();
var Receive = (function () {
    function Receive(value0) {
        this.value0 = value0;
    };
    Receive.create = function (value0) {
        return new Receive(value0);
    };
    return Receive;
})();
var LoadArticles = (function () {
    function LoadArticles() {

    };
    LoadArticles.value = new LoadArticles();
    return LoadArticles;
})();
var LoadFavorites = (function () {
    function LoadFavorites() {

    };
    LoadFavorites.value = new LoadFavorites();
    return LoadFavorites;
})();
var LoadAuthor = (function () {
    function LoadAuthor() {

    };
    LoadAuthor.value = new LoadAuthor();
    return LoadAuthor;
})();
var FollowAuthor = (function () {
    function FollowAuthor() {

    };
    FollowAuthor.value = new FollowAuthor();
    return FollowAuthor;
})();
var UnfollowAuthor = (function () {
    function UnfollowAuthor() {

    };
    UnfollowAuthor.value = new UnfollowAuthor();
    return UnfollowAuthor;
})();
var FavoriteArticle = (function () {
    function FavoriteArticle(value0) {
        this.value0 = value0;
    };
    FavoriteArticle.create = function (value0) {
        return new FavoriteArticle(value0);
    };
    return FavoriteArticle;
})();
var UnfavoriteArticle = (function () {
    function UnfavoriteArticle(value0) {
        this.value0 = value0;
    };
    UnfavoriteArticle.create = function (value0) {
        return new UnfavoriteArticle(value0);
    };
    return UnfavoriteArticle;
})();
var SelectPage = (function () {
    function SelectPage(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    SelectPage.create = function (value0) {
        return function (value1) {
            return new SelectPage(value0, value1);
        };
    };
    return SelectPage;
})();
var eqTab = new Data_Eq.Eq(function (x) {
    return function (y) {
        if (x instanceof ArticlesTab && y instanceof ArticlesTab) {
            return true;
        };
        if (x instanceof FavoritesTab && y instanceof FavoritesTab) {
            return true;
        };
        return false;
    };
});
var _author = function (dictWander) {
    var $684 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "author";
    }))()()(Data_Symbol.SProxy.value)(dictWander.Strong0());
    var $685 = Network_RemoteData["_Success"](dictWander.Choice1());
    return function ($686) {
        return $684($685($686));
    };
};
var _article = function (i) {
    return function (dictWander) {
        var $687 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "articles";
        }))()()(Data_Symbol.SProxy.value)(dictWander.Strong0());
        var $688 = Network_RemoteData["_Success"](dictWander.Choice1());
        var $689 = Data_Lens_Record.prop(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "body";
        }))()()(Data_Symbol.SProxy.value)(dictWander.Strong0());
        var $690 = Data_Lens_Index.ix(Data_Lens_Index.indexArray)(i)(dictWander);
        return function ($691) {
            return $687($688($689($690($691))));
        };
    };
};
var component = function (dictMonadAff) {
    return function (dictMonadAsk) {
        return function (dictManageUser) {
            return function (dictManageArticle) {
                var render = function (state) {
                    var userInfo = Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("user-info") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("container") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("row") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("col-xs-12 col-md-10 offset-md-1") ])([ Halogen_HTML_Elements.img([ Conduit_Component_HTML_Utils.css("user-img"), Halogen_HTML_Properties.src(Conduit_Data_Avatar.toStringWithDefault(Control_Bind.bindFlipped(Data_Maybe.bindMaybe)(function (v) {
                        return v.image;
                    })(Network_RemoteData.toMaybe(state.author)))) ]), Halogen_HTML_Elements.h4_([ Halogen_HTML_Core.text(Conduit_Data_Username.toString(state.username)) ]), Conduit_Component_HTML_Utils.maybeElem(Control_Bind.bindFlipped(Data_Maybe.bindMaybe)(function (v) {
                        return v.bio;
                    })(Network_RemoteData.toMaybe(state.author)))(function (str) {
                        return Halogen_HTML_Elements.p_([ Halogen_HTML_Core.text(str) ]);
                    }), Conduit_Component_HTML_Utils.maybeElem(Network_RemoteData.toMaybe(state.author))(Conduit_Component_Part_FollowButton.followButton(FollowAuthor.value)(UnfollowAuthor.value)) ]) ]) ]) ]);
                    var mkTab = function (thisTab) {
                        return Halogen_HTML_Elements.li([ Conduit_Component_HTML_Utils.css("nav-item") ])([ (function () {
                            if (thisTab instanceof ArticlesTab) {
                                return Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("nav-link" + Data_Monoid.guard(Data_Monoid.monoidString)(Data_Eq.eq(eqTab)(state.tab)(thisTab))(" active")), Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.Profile(state.username)) ])([ Halogen_HTML_Core.text("My Articles") ]);
                            };
                            if (thisTab instanceof FavoritesTab) {
                                return Halogen_HTML_Elements.a([ Conduit_Component_HTML_Utils.css("nav-link" + Data_Monoid.guard(Data_Monoid.monoidString)(Data_Eq.eq(eqTab)(state.tab)(thisTab))(" active")), Conduit_Component_HTML_Utils.safeHref(new Conduit_Data_Route.Favorites(state.username)) ])([ Halogen_HTML_Core.text("My Favorites") ]);
                            };
                            throw new Error("Failed pattern match at Conduit.Page.Profile (line 237, column 11 - line 249, column 43): " + [ thisTab.constructor.name ]);
                        })() ]);
                    };
                    var mainView = Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("col-xs-12 col-md-10 offset-md-1") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("articles-toggle") ])([ Halogen_HTML_Elements.ul([ Conduit_Component_HTML_Utils.css("nav nav-pills outline-active") ])([ mkTab(ArticlesTab.value), mkTab(FavoritesTab.value) ]) ]), Conduit_Component_HTML_Utils.whenElem(Data_Eq.eq(eqTab)(state.tab)(ArticlesTab.value))(function (v) {
                        return Halogen_HTML_Elements.div_([ Conduit_Component_HTML_ArticleList.articleList(FavoriteArticle.create)(UnfavoriteArticle.create)(state.articles), Conduit_Component_HTML_Utils.maybeElem(Network_RemoteData.toMaybe(state.articles))(function (paginated) {
                            return Conduit_Component_HTML_ArticleList.renderPagination(SelectPage.create)(state.page)(paginated);
                        }) ]);
                    }), Conduit_Component_HTML_Utils.whenElem(Data_Eq.eq(eqTab)(state.tab)(FavoritesTab.value))(function (v) {
                        return Halogen_HTML_Elements.div_([ Conduit_Component_HTML_ArticleList.articleList(FavoriteArticle.create)(UnfavoriteArticle.create)(state.favorites), Conduit_Component_HTML_Utils.maybeElem(Network_RemoteData.toMaybe(state.favorites))(function (paginated) {
                            return Conduit_Component_HTML_ArticleList.renderPagination(SelectPage.create)(state.page)(paginated);
                        }) ]);
                    }) ]);
                    return Halogen_HTML_Elements.div_([ Conduit_Component_HTML_Header.header(state.currentUser)(new Conduit_Data_Route.Profile(state.username)), Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("profile-page") ])([ userInfo, Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("container") ])([ Halogen_HTML_Elements.div([ Conduit_Component_HTML_Utils.css("row") ])([ mainView ]) ]) ]), Conduit_Component_HTML_Footer.footer ]);
                };
                var initialState = function (v) {
                    return {
                        articles: Network_RemoteData.NotAsked.value,
                        favorites: Network_RemoteData.NotAsked.value,
                        author: Network_RemoteData.NotAsked.value,
                        currentUser: Data_Maybe.Nothing.value,
                        page: 1,
                        tab: v.tab,
                        username: v.username
                    };
                };
                var handleAction = function (v) {
                    if (v instanceof Initialize) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Bind.bindFlipped(Halogen_Query_HalogenM.bindHalogenM)((function () {
                            var $692 = Effect_Class.liftEffect(Halogen_Query_HalogenM.monadEffectHalogenM(dictMonadAff.MonadEffect0()));
                            return function ($693) {
                                return $692(Effect_Ref.read($693));
                            };
                        })())(Control_Monad_Reader_Class.asks(Halogen_Query_HalogenM.monadAskHalogenM(dictMonadAsk))(function (v1) {
                            return v1.userEnv.currentUser;
                        })))(function (mbProfile) {
                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                var $642 = {};
                                for (var $643 in v1) {
                                    if ({}.hasOwnProperty.call(v1, $643)) {
                                        $642[$643] = v1[$643];
                                    };
                                };
                                $642.currentUser = mbProfile;
                                return $642;
                            }))(function (st) {
                                return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Halogen_Query_HalogenM.fork(handleAction(LoadAuthor.value))))(function ($dollar__unused) {
                                    return Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Halogen_Query_HalogenM.fork((function () {
                                        if (st.tab instanceof ArticlesTab) {
                                            return handleAction(LoadArticles.value);
                                        };
                                        if (st.tab instanceof FavoritesTab) {
                                            return handleAction(LoadFavorites.value);
                                        };
                                        throw new Error("Failed pattern match at Conduit.Page.Profile (line 109, column 23 - line 111, column 51): " + [ st.tab.constructor.name ]);
                                    })()));
                                });
                            });
                        });
                    };
                    if (v instanceof Receive) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.get(Halogen_Query_HalogenM.monadStateHalogenM))(function (st) {
                            return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Applicative.when(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Eq.notEq(eqTab)(st.tab)(v.value0.tab))(Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                var $646 = {};
                                for (var $647 in v1) {
                                    if ({}.hasOwnProperty.call(v1, $647)) {
                                        $646[$647] = v1[$647];
                                    };
                                };
                                $646.tab = v.value0.tab;
                                return $646;
                            }))(function ($dollar__unused) {
                                return Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Halogen_Query_HalogenM.fork((function () {
                                    if (v.value0.tab instanceof ArticlesTab) {
                                        return handleAction(LoadArticles.value);
                                    };
                                    if (v.value0.tab instanceof FavoritesTab) {
                                        return handleAction(LoadFavorites.value);
                                    };
                                    throw new Error("Failed pattern match at Conduit.Page.Profile (line 117, column 25 - line 119, column 53): " + [ v.value0.tab.constructor.name ]);
                                })()));
                            })))(function ($dollar__unused) {
                                return Control_Applicative.when(Halogen_Query_HalogenM.applicativeHalogenM)(Data_Eq.notEq(Conduit_Data_Username.eqUsername)(st.username)(v.value0.username))(Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $650 = {};
                                    for (var $651 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $651)) {
                                            $650[$651] = v1[$651];
                                        };
                                    };
                                    $650.username = v.value0.username;
                                    return $650;
                                }))(function ($dollar__unused) {
                                    return Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Halogen_Query_HalogenM.fork(handleAction(Initialize.value)));
                                }));
                            });
                        });
                    };
                    if (v instanceof LoadArticles) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                            var $656 = {};
                            for (var $657 in v1) {
                                if ({}.hasOwnProperty.call(v1, $657)) {
                                    $656[$657] = v1[$657];
                                };
                            };
                            $656.articles = Network_RemoteData.Loading.value;
                            return $656;
                        }))(function (st) {
                            var params = {
                                author: new Data_Maybe.Just(st.username),
                                offset: (function () {
                                    var $659 = st.page > 1;
                                    if ($659) {
                                        return new Data_Maybe.Just(st.page * 20 | 0);
                                    };
                                    return Data_Maybe.Nothing.value;
                                })(),
                                favorited: Conduit_Api_Endpoint.noArticleParams.favorited,
                                limit: Conduit_Api_Endpoint.noArticleParams.limit,
                                tag: Conduit_Api_Endpoint.noArticleParams.tag
                            };
                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Article.getArticles(Conduit_Capability_Resource_Article.manageArticleHalogenM(dictManageArticle))(params))(function (articles) {
                                return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $660 = {};
                                    for (var $661 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $661)) {
                                            $660[$661] = v1[$661];
                                        };
                                    };
                                    $660.articles = Network_RemoteData.fromMaybe(articles);
                                    return $660;
                                });
                            });
                        });
                    };
                    if (v instanceof LoadFavorites) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                            var $663 = {};
                            for (var $664 in v1) {
                                if ({}.hasOwnProperty.call(v1, $664)) {
                                    $663[$664] = v1[$664];
                                };
                            };
                            $663.favorites = Network_RemoteData.Loading.value;
                            return $663;
                        }))(function (st) {
                            var params = {
                                favorited: new Data_Maybe.Just(st.username),
                                offset: (function () {
                                    var $666 = st.page > 1;
                                    if ($666) {
                                        return new Data_Maybe.Just(st.page * 20 | 0);
                                    };
                                    return Data_Maybe.Nothing.value;
                                })(),
                                author: Conduit_Api_Endpoint.noArticleParams.author,
                                limit: Conduit_Api_Endpoint.noArticleParams.limit,
                                tag: Conduit_Api_Endpoint.noArticleParams.tag
                            };
                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_Article.getArticles(Conduit_Capability_Resource_Article.manageArticleHalogenM(dictManageArticle))(params))(function (favorites) {
                                return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $667 = {};
                                    for (var $668 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $668)) {
                                            $667[$668] = v1[$668];
                                        };
                                    };
                                    $667.favorites = Network_RemoteData.fromMaybe(favorites);
                                    return $667;
                                });
                            });
                        });
                    };
                    if (v instanceof LoadAuthor) {
                        return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                            var $670 = {};
                            for (var $671 in v1) {
                                if ({}.hasOwnProperty.call(v1, $671)) {
                                    $670[$671] = v1[$671];
                                };
                            };
                            $670.author = Network_RemoteData.Loading.value;
                            return $670;
                        }))(function (st) {
                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Conduit_Capability_Resource_User.getAuthor(Conduit_Capability_Resource_User.manageUserHalogenM(dictManageUser))(st.username))(function (author) {
                                return Control_Monad_State_Class.modify_(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                    var $673 = {};
                                    for (var $674 in v1) {
                                        if ({}.hasOwnProperty.call(v1, $674)) {
                                            $673[$674] = v1[$674];
                                        };
                                    };
                                    $673.author = Network_RemoteData.fromMaybe(author);
                                    return $673;
                                });
                            });
                        });
                    };
                    if (v instanceof FollowAuthor) {
                        return Conduit_Component_Part_FollowButton.follow(dictManageUser)(function (dictWander) {
                            return _author(dictWander);
                        });
                    };
                    if (v instanceof UnfollowAuthor) {
                        return Conduit_Component_Part_FollowButton.unfollow(dictManageUser)(function (dictWander) {
                            return _author(dictWander);
                        });
                    };
                    if (v instanceof FavoriteArticle) {
                        return Conduit_Component_Part_FavoriteButton.favorite(dictManageArticle)(function (dictWander) {
                            return _article(v.value0)(dictWander);
                        });
                    };
                    if (v instanceof UnfavoriteArticle) {
                        return Conduit_Component_Part_FavoriteButton.unfavorite(dictManageArticle)(function (dictWander) {
                            return _article(v.value0)(dictWander);
                        });
                    };
                    if (v instanceof SelectPage) {
                        return Control_Bind.discard(Control_Bind.discardUnit)(Halogen_Query_HalogenM.bindHalogenM)(Effect_Class.liftEffect(Halogen_Query_HalogenM.monadEffectHalogenM(dictMonadAff.MonadEffect0()))(Web_Event_Event.preventDefault(Web_UIEvent_MouseEvent.toEvent(v.value1))))(function ($dollar__unused) {
                            return Control_Bind.bind(Halogen_Query_HalogenM.bindHalogenM)(Control_Monad_State_Class.modify(Halogen_Query_HalogenM.monadStateHalogenM)(function (v1) {
                                var $678 = {};
                                for (var $679 in v1) {
                                    if ({}.hasOwnProperty.call(v1, $679)) {
                                        $678[$679] = v1[$679];
                                    };
                                };
                                $678.page = v.value0;
                                return $678;
                            }))(function (st) {
                                return Data_Functor["void"](Halogen_Query_HalogenM.functorHalogenM)(Halogen_Query_HalogenM.fork(handleAction((function () {
                                    if (st.tab instanceof FavoritesTab) {
                                        return LoadFavorites.value;
                                    };
                                    if (st.tab instanceof ArticlesTab) {
                                        return LoadArticles.value;
                                    };
                                    throw new Error("Failed pattern match at Conduit.Page.Profile (line 164, column 36 - line 166, column 36): " + [ st.tab.constructor.name ]);
                                })())));
                            });
                        });
                    };
                    throw new Error("Failed pattern match at Conduit.Page.Profile (line 104, column 18 - line 166, column 36): " + [ v.constructor.name ]);
                };
                return Halogen_Component.mkComponent({
                    initialState: initialState,
                    render: render,
                    "eval": Halogen_Component.mkEval({
                        handleAction: handleAction,
                        handleQuery: Halogen_Component.defaultEval.handleQuery,
                        receive: function ($694) {
                            return Data_Maybe.Just.create(Receive.create($694));
                        },
                        initialize: new Data_Maybe.Just(Initialize.value),
                        finalize: Halogen_Component.defaultEval.finalize
                    })
                });
            };
        };
    };
};
module.exports = {
    Initialize: Initialize,
    Receive: Receive,
    LoadArticles: LoadArticles,
    LoadFavorites: LoadFavorites,
    LoadAuthor: LoadAuthor,
    FollowAuthor: FollowAuthor,
    UnfollowAuthor: UnfollowAuthor,
    FavoriteArticle: FavoriteArticle,
    UnfavoriteArticle: UnfavoriteArticle,
    SelectPage: SelectPage,
    ArticlesTab: ArticlesTab,
    FavoritesTab: FavoritesTab,
    component: component,
    "_author": _author,
    "_article": _article,
    eqTab: eqTab
};
