// Generated by purs version 0.13.8
"use strict";
var Data_Newtype = require("../Data.Newtype/index.js");
var Replacement = function (x) {
    return x;
};
var Pattern = function (x) {
    return x;
};
var newtypePattern = new Data_Newtype.Newtype(function (n) {
    return n;
}, Pattern);
module.exports = {
    Pattern: Pattern,
    Replacement: Replacement,
    newtypePattern: newtypePattern
};
